import { useEffect,useState } from 'react';
import { CheckCircle2,Globe2,Plus,RefreshCw,Trash2 } from 'lucide-react';
import { api } from '../state';
import { Badge,Button,Dialog,PageHead } from '../components';

const blank={empresa_id:'',dominio:'',tipo:'Dominio',principal:false,destino_esperado:''};
export default function Dominios(){
  const[items,setItems]=useState<any[]>([]),[companies,setCompanies]=useState<any[]>([]),[open,setOpen]=useState(false),[value,setValue]=useState<any>(blank),[error,setError]=useState('');
  const load=()=>Promise.all([api('/dominios'),api('/empresas')]).then(([domains,businesses])=>{setItems(domains);setCompanies(businesses)});
  useEffect(()=>{load()},[]);
  const save=async(event:any)=>{event.preventDefault();setError('');try{await api('/dominios',{method:'POST',body:JSON.stringify(value)});setOpen(false);setValue(blank);load()}catch(reason){setError((reason as Error).message)}};
  return <><PageHead title="Dominios" subtitle="Dominios, subdominios y verificación DNS por empresa" action={<Button onClick={()=>setOpen(true)}><Plus size={18}/>Asignar dominio</Button>}/>
    <div className="space-y-4">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950"><Globe2/></span><div><h3 className="font-bold">{item.dominio}</h3><p className="text-xs text-slate-500">{item.empresa.nombre} · {item.tipo}{item.principal?' · Principal':''}</p></div></div><Badge tone={item.estado==='Activo'?'green':item.estado==='Error_DNS'?'red':'amber'}>{item.estado}</Badge></div>
      <div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-950"><b>Verificación requerida</b><p className="mt-1 text-xs text-slate-500">Crea un registro TXT con nombre <code>_seguridadpro-verification.{item.dominio}</code> y valor:</p><code className="mt-2 block break-all rounded bg-slate-200 p-2 text-xs dark:bg-slate-800">{item.token_verificacion}</code>{item.destino_esperado&&<p className="mt-2 text-xs text-slate-500">El registro A/AAAA o CNAME debe apuntar a: <b>{item.destino_esperado}</b></p>}{item.ultimo_error&&<p className="mt-2 text-xs text-red-600">{item.ultimo_error}</p>}</div>
      <div className="mt-3 flex justify-end gap-2"><Button variant="secondary" onClick={async()=>{try{const result=await api(`/dominios/${item.id}/verificar`,{method:'POST'});alert(result.dns.verified?'Dominio verificado correctamente':'La verificación DNS todavía no está completa');load()}catch(reason){alert((reason as Error).message)}}}>{item.estado==='Activo'?<CheckCircle2 size={16}/>:<RefreshCw size={16}/>}Verificar</Button><button className="rounded-xl p-2 text-red-600 hover:bg-red-50" onClick={async()=>{if(confirm('¿Eliminar este dominio?')){await api('/dominios/'+item.id,{method:'DELETE'});load()}}}><Trash2 size={17}/></button></div>
    </article>)}</div>
    <Dialog open={open} onClose={()=>setOpen(false)} title="Asignar dominio"><form onSubmit={save} className="space-y-4"><Select label="Empresa" value={value.empresa_id} set={(next:string)=>setValue({...value,empresa_id:next})} options={companies.map(item=>[item.id,item.nombre])}/><Field label="Dominio o subdominio" placeholder="seguridad.empresa.cl" value={value.dominio} set={(next:string)=>setValue({...value,dominio:next})}/><Select label="Tipo" value={value.tipo} set={(next:string)=>setValue({...value,tipo:next})} options={[["Dominio","Dominio propio"],["Subdominio","Subdominio propio"],["SubdominioSistema","Subdominio SeguridadPro"]]}/><Field label="IP o CNAME esperado" placeholder="203.0.113.20" value={value.destino_esperado} set={(next:string)=>setValue({...value,destino_esperado:next})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.principal} onChange={event=>setValue({...value,principal:event.target.checked})}/>Dominio principal de la empresa</label>{error&&<p className="text-sm text-red-600">{error}</p>}<Button className="w-full">Guardar dominio</Button></form></Dialog>
  </>;
}
function Field({label,set,...props}:any){return <label className="block text-sm font-semibold">{label}<input {...props} required onChange={event=>set(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 dark:border-slate-700"/></label>}
function Select({label,value,set,options}:any){return <label className="block text-sm font-semibold">{label}<select required value={value} onChange={event=>set(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-2.5 dark:border-slate-700 dark:bg-slate-900"><option value="">Selecciona…</option>{options.map(([id,name]:string[])=><option key={id} value={id}>{name}</option>)}</select></label>}
