import { useState, type FormEvent } from 'react';
import { ArrowRight, Lock, Mail, Shield } from 'lucide-react';
import { api, useAuth } from '../state';
import { useBranding } from '../branding';

export default function Login(){
  const{login}=useAuth();const{branding}=useBranding();
  const[mode,setMode]=useState<'login'|'forgot'>('login');
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');
  const[error,setError]=useState('');const[msg,setMsg]=useState('');
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{if(mode==='login')await login(email,password);else{const d=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});setMsg(d.message)}}catch(e){setError((e as Error).message)}};
  const Logo=()=>branding.logo_url?<img src={branding.logo_url} alt={branding.brand_name} className="h-11 max-w-52 object-contain"/>:<span className="inline-flex items-center gap-2 text-xl font-bold"><span className="grid size-11 place-items-center rounded-xl bg-white/15"><Shield/></span>{branding.brand_name}</span>;
  return <main className="grid min-h-screen bg-slate-950 lg:grid-cols-2"><section className="brand-bg relative hidden overflow-hidden p-16 text-white lg:flex lg:flex-col lg:justify-between" style={branding.hero_image_url?{backgroundImage:`linear-gradient(90deg,rgba(15,23,42,.88),rgba(15,23,42,.45)),url(${branding.hero_image_url})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><div className="absolute -right-32 -top-32 size-[34rem] rounded-full border-[90px] border-white/5"/><Logo/><div className="relative max-w-xl"><p className="mb-5 text-sm font-semibold uppercase tracking-[.25em] text-white/70">{branding.brand_subtitle}</p><h1 className="text-5xl font-bold leading-tight">{branding.hero_title}</h1><p className="mt-6 text-lg text-white/80">{branding.hero_description}</p></div><p className="text-sm text-white/70">{branding.hero_footer}</p></section><section className="flex items-center justify-center bg-[#f6f8f7] p-5 dark:bg-slate-950"><div className="w-full max-w-md rounded-3xl bg-white p-7 shadow-xl shadow-slate-900/5 dark:bg-slate-900 sm:p-10"><div className="brand-text mb-8 lg:hidden"><Logo/></div><h2 className="text-2xl font-bold">{mode==='login'?'Bienvenido de vuelta':'Recupera tu acceso'}</h2><p className="mt-2 text-sm text-slate-500">{mode==='login'?'Ingresa tus credenciales para continuar.':'Te enviaremos un código de recuperación.'}</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-semibold">Correo electrónico<div className="relative mt-2"><Mail className="absolute left-3 top-3 text-slate-400" size={20}/><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border border-slate-200 py-3 pl-11 pr-3 dark:border-slate-700 dark:bg-slate-950" required/></div></label>{mode==='login'&&<label className="block text-sm font-semibold">Contraseña<div className="relative mt-2"><Lock className="absolute left-3 top-3 text-slate-400" size={20}/><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border border-slate-200 py-3 pl-11 pr-3 dark:border-slate-700 dark:bg-slate-950" required/></div></label>}{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{msg&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</p>}<button className="brand-bg flex w-full items-center justify-center gap-2 rounded-xl py-3 font-semibold text-white">{mode==='login'?'Ingresar':'Enviar código'}<ArrowRight size={18}/></button></form><button onClick={()=>setMode(mode==='login'?'forgot':'login')} className="brand-text mt-5 w-full text-sm font-semibold">{mode==='login'?'¿Olvidaste tu contraseña?':'Volver al inicio de sesión'}</button></div></section></main>;
}
