import { useEffect,useState } from 'react';
import { Building2,Globe2,Save,ShieldCheck } from 'lucide-react';
import { api } from '../state';
import { Badge,Button,PageHead } from '../components';

export default function MiEmpresa(){
  const[value,setValue]=useState<any>(null),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{api('/mi-empresa').then(setValue).catch(reason=>setError((reason as Error).message))},[]);
  if(!value)return <div className="rounded-2xl bg-white p-8 text-sm text-slate-500 dark:bg-slate-900">{error||'Cargando datos de la empresa…'}</div>;
  const set=(key:string,next:any)=>setValue({...value,[key]:next});
  const save=async(event:any)=>{event.preventDefault();setMessage('');setError('');try{const updated=await api('/mi-empresa',{method:'PUT',body:JSON.stringify(Object.fromEntries(['nombre','rut','email','telefono','direccion','logo_url','website_url','descripcion','servicios','quote_email','public_page_enabled'].map(key=>[key,value[key]])))});setValue({...value,...updated});setMessage('Datos de la empresa guardados correctamente')}catch(reason){setError((reason as Error).message)}};
  return <><PageHead title="Mi empresa" subtitle="Información comercial, página pública y contrato"/>
    <div className="grid gap-5 xl:grid-cols-[1fr_340px]"><form onSubmit={save} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
      <section><h2 className="mb-3 flex items-center gap-2 font-bold"><Building2 size={19}/>Datos comerciales</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre de la empresa" value={value.nombre} set={(next:string)=>set('nombre',next)} required/><Field label="RUT" value={value.rut} set={(next:string)=>set('rut',next)}/><Field label="Correo comercial" type="email" value={value.email} set={(next:string)=>set('email',next)}/><Field label="Teléfono" value={value.telefono} set={(next:string)=>set('telefono',next)}/><Field label="Dirección" value={value.direccion} set={(next:string)=>set('direccion',next)}/><Field label="Sitio web" type="url" value={value.website_url} set={(next:string)=>set('website_url',next)} placeholder="https://empresa.cl"/><Field label="URL del logotipo" value={value.logo_url} set={(next:string)=>set('logo_url',next)}/><Field label="Correo de cotizaciones" type="email" value={value.quote_email} set={(next:string)=>set('quote_email',next)}/></div></section>
      <section><h2 className="mb-3 flex items-center gap-2 font-bold"><Globe2 size={19}/>Página pública</h2><label className="mb-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm font-semibold dark:bg-slate-950"><input type="checkbox" checked={!!value.public_page_enabled} onChange={event=>set('public_page_enabled',event.target.checked)}/>Activar página pública de la empresa</label><div className="space-y-4"><Area label="Descripción de la empresa" value={value.descripcion} set={(next:string)=>set('descripcion',next)}/><Area label="Servicios ofrecidos" value={value.servicios} set={(next:string)=>set('servicios',next)}/></div></section>
      {message&&<p className="text-sm text-emerald-600">{message}</p>}{error&&<p className="text-sm text-red-600">{error}</p>}<Button><Save size={17}/>Guardar datos</Button>
    </form><aside className="space-y-5"><Card title="Contrato"><Row label="Estado" value={<Badge tone={value.estado==='Activa'?'green':'red'}>{value.estado}</Badge>}/><Row label="Vencimiento" value={value.vence_at?new Date(value.vence_at).toLocaleDateString('es-CL'):'Sin vencimiento'}/><Row label="Identificador" value={value.slug}/></Card><Card title="Uso actual"><Row label="Usuarios" value={`${value._count.users} / ${value.limite_usuarios||'∞'}`}/><Row label="Guardias" value={`${value._count.guardias} / ${value.limite_guardias||'∞'}`}/><Row label="Recintos" value={`${value._count.recintos} / ${value.limite_recintos||'∞'}`}/><Row label="Turnos" value={value._count.turnos}/></Card><Card title="Módulos contratados"><div className="flex flex-wrap gap-2">{Object.entries(value.modulos||{}).filter(entry=>entry[1]).map(entry=><Badge key={entry[0]} tone="blue">{entry[0]}</Badge>)}</div></Card><Card title="Dominios"><div className="space-y-2">{value.dominios.length?value.dominios.map((domain:any)=><div key={domain.id} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-950"><b className="block break-all">{domain.dominio}</b><span className="text-xs text-slate-500">{domain.estado}{domain.principal?' · Principal':''}</span></div>):<p className="text-sm text-slate-500">No hay dominios asignados.</p>}</div></Card><div className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-800 dark:bg-blue-950/40 dark:text-blue-200"><ShieldCheck className="mb-2"/><b>Información protegida</b><p className="mt-1 text-xs">Plan, módulos, límites, vencimiento y dominios son administrados por SeguridadPro.</p></div></aside></div>
  </>;
}
function Field({label,set,...props}:any){return <label className="text-sm font-semibold">{label}<input {...props} value={props.value||''} onChange={event=>set(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 dark:border-slate-700"/></label>}
function Area({label,value,set}:any){return <label className="block text-sm font-semibold">{label}<textarea rows={4} value={value||''} onChange={event=>set(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 dark:border-slate-700"/></label>}
function Card({title,children}:{title:string;children:any}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 className="mb-3 font-bold">{title}</h3>{children}</section>}
function Row({label,value}:{label:string;value:any}){return <div className="flex items-center justify-between gap-3 border-b border-slate-100 py-2 text-sm last:border-0 dark:border-slate-800"><span className="text-slate-500">{label}</span><span className="text-right font-semibold">{value}</span></div>}
