import{useEffect,useMemo,useState}from'react';
import{CalendarDays,CalendarPlus,ChevronLeft,ChevronRight,List,Pencil,Trash2}from'lucide-react';
import{api,useAuth}from'../state';import{Badge,Button,Dialog,PageHead,toneFor}from'../components';
import WeeklyGrid from'../WeeklyGrid';
type PeriodView='day'|'week'|'month'|'list';
const today=()=>new Date().toLocaleDateString('en-CA');
const startOfDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const weekStart=(d:Date)=>addDays(startOfDay(d),-((d.getDay()+6)%7));
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
const localDate=(value:string|Date)=>{if(value instanceof Date)return value;const match=String(value).slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3])):new Date(value)};
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const workDays=[[1,'Lunes'],[2,'Martes'],[3,'Miércoles'],[4,'Jueves'],[5,'Viernes'],[6,'Sábado'],[7,'Domingo']] as const;
const shiftHours=(start:string,end:string)=>{if(!start||!end)return 0;const minutes=(value:string)=>{const[h,m]=value.split(':').map(Number);return h*60+m},a=minutes(start),b=minutes(end);return((b>a?b:b+1440)-a)/60};
const blank=()=>({guardia_nombre:'',recinto_nombre:'',tipo_turno:'Dia',periodo:'dia',dias_semana:[1,2,3,4,5],fecha:today(),hora_inicio:'08:00',hora_fin:'20:00',ubicacion:'',observaciones:'',estado:'Programado'});

export default function Turnos(){
 const{user}=useAuth();const canEdit=user?.role==='admin'||(user?.role!=='guardia'&&user?.permisos?.editar_turnos===true);const canDelete=user?.role==='admin'||(user?.role!=='guardia'&&user?.permisos?.eliminar_turnos===true);
 const[items,setItems]=useState<any[]>([]),[guardias,setGuardias]=useState<any[]>([]),[recintos,setRecintos]=useState<any[]>([]);
 const[config,setConfig]=useState<any>({turno_dia_inicio:'08:00',turno_dia_fin:'20:00',turno_manana_inicio:'08:00',turno_manana_fin:'16:00',turno_tarde_inicio:'16:00',turno_tarde_fin:'00:00',turno_noche_inicio:'20:00',turno_noche_fin:'08:00',turno_dia_color:'#f59e0b',turno_noche_color:'#2563eb',turno_personalizado_color:'#7c3aed'});
 const[v,setV]=useState<any>(blank()),[editing,setEditing]=useState<any>(null),[open,setOpen]=useState(false),[error,setError]=useState('');
 const[periodView,setPeriodView]=useState<PeriodView>('week'),[anchorDate,setAnchorDate]=useState(()=>startOfDay(new Date()));
 const load=()=>api('/turno?limit=500').then(x=>setItems(x.data));
 useEffect(()=>{load();api('/lookups/guardias').then(setGuardias);api('/lookups/recintos').then(setRecintos);api('/config').then(setConfig).catch(()=>{})},[]);
 const range=useMemo(()=>{if(periodView==='list')return null;if(periodView==='day')return{start:startOfDay(anchorDate),end:addDays(startOfDay(anchorDate),1)};if(periodView==='week'){const start=weekStart(anchorDate);return{start,end:addDays(start,7)}}return{start:new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1),end:new Date(anchorDate.getFullYear(),anchorDate.getMonth()+1,1)}},[anchorDate,periodView]);
 const visible=useMemo(()=>items.filter(x=>!range||((d=>!Number.isNaN(d.getTime())&&d>=range.start&&d<range.end)(localDate(x.fecha)))),[items,range]);
 const label=periodView==='list'?'Todos los turnos':periodView==='day'?anchorDate.toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'}):periodView==='week'?`${range!.start.toLocaleDateString('es-CL',{day:'numeric',month:'short'})} – ${addDays(range!.end,-1).toLocaleDateString('es-CL',{day:'numeric',month:'short',year:'numeric'})}`:anchorDate.toLocaleDateString('es-CL',{month:'long',year:'numeric'});
 const move=(n:number)=>setAnchorDate(d=>periodView==='day'?addDays(d,n):periodView==='week'?addDays(d,n*7):new Date(d.getFullYear(),d.getMonth()+n,1));
 const monthStart=new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1),calendarStart=addDays(monthStart,-((monthStart.getDay()+6)%7));
 const calendarDays=Array.from({length:42},(_,i)=>addDays(calendarStart,i));
 const weekDays=Array.from({length:7},(_,i)=>addDays(weekStart(anchorDate),i));
 const applyType=(type:string)=>setV((x:any)=>({...x,tipo_turno:type,...(type==='Dia'?{hora_inicio:config.turno_dia_inicio,hora_fin:config.turno_dia_fin}:type==='Noche'?{hora_inicio:config.turno_noche_inicio,hora_fin:config.turno_noche_fin}:type==='Manana'?{hora_inicio:config.turno_manana_inicio,hora_fin:config.turno_manana_fin}:type==='Tarde'?{hora_inicio:config.turno_tarde_inicio,hora_fin:config.turno_tarde_fin}:{hora_inicio:'',hora_fin:''})}));
 const begin=(x?:any)=>{setEditing(x||null);setV(x?{...x,fecha:String(x.fecha).slice(0,10),periodo:'dia'}:{...blank(),hora_inicio:config.turno_dia_inicio,hora_fin:config.turno_dia_fin});setOpen(true)};
 const beginAt=(guardia:any,d:Date)=>{setEditing(null);setV({...blank(),guardia_nombre:guardia.nombre,fecha:dateKey(d),hora_inicio:config.turno_dia_inicio,hora_fin:config.turno_dia_fin});setOpen(true)};
 const selectedDays=(v.dias_semana||[]) as number[],hoursPerShift=shiftHours(v.hora_inicio,v.hora_fin),weeklyHours=hoursPerShift*selectedDays.length;
 const toggleDay=(day:number)=>setV({...v,dias_semana:selectedDays.includes(day)?selectedDays.filter(x=>x!==day):[...selectedDays,day].sort((a,b)=>a-b)});
 const save=async(e:any)=>{e.preventDefault();setError('');try{const g=guardias.find(x=>x.nombre===v.guardia_nombre),r=recintos.find(x=>x.nombre===v.recinto_nombre);if(!g?.id){setError('Debe seleccionar un guardia válido.');return}if(!v.fecha||!v.hora_inicio||!v.hora_fin){setError('Guardia, fecha y horario son obligatorios.');return}if(v.hora_inicio===v.hora_fin){setError('La hora de inicio y término deben ser diferentes.');return}if(!editing&&v.periodo==='semana'&&!selectedDays.length){setError('Selecciona al menos un día de trabajo.');return}if(!editing&&v.periodo==='semana'&&weeklyHours>45){setError('La programación supera el máximo semanal de 45 horas.');return}const data={...v,guardia_id:g.id,guardia_nombre:g.nombre,recinto_id:r?.id||null,recinto_nombre:r?.nombre||null};if(editing){const{periodo,...updateData}=data;await api('/turno/'+editing.id,{method:'PUT',body:JSON.stringify(updateData)})}else await api('/turnos/programar',{method:'POST',body:JSON.stringify(data)});setOpen(false);await load()}catch(e){setError((e as Error).message)}};
 return <><PageHead title="Turnos" subtitle="Planificación diaria, semanal y mensual" action={canEdit?<Button onClick={()=>begin()}><CalendarPlus size={16}/>Programar</Button>:undefined}/>
 <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800/80"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{([['day','Día'],['week','Semana'],['month','Mes'],['list','Lista']]as[PeriodView,string][]).map(([x,t])=><button key={x} onClick={()=>setPeriodView(x)} className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold ${periodView===x?'bg-teal-600 text-white':'bg-slate-100 text-slate-600 hover:bg-slate-200 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600'}`}>{x==='month'?<CalendarDays size={15}/>:x==='list'?<List size={15}/>:null}{t}</button>)}</div><div className="flex items-center gap-1"><button onClick={()=>move(-1)} disabled={periodView==='list'} className="rounded-lg p-1.5 hover:bg-slate-100 disabled:opacity-30 dark:hover:bg-slate-700"><ChevronLeft size={18}/></button><button onClick={()=>setAnchorDate(startOfDay(new Date()))} className="rounded-lg px-3 py-1.5 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-slate-700">Hoy</button><button onClick={()=>move(1)} disabled={periodView==='list'} className="rounded-lg p-1.5 hover:bg-slate-100 disabled:opacity-30 dark:hover:bg-slate-700"><ChevronRight size={18}/></button></div></div><div className="mt-3 flex justify-between gap-2"><h2 className="font-bold capitalize">{label}</h2><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-700 dark:bg-teal-900/50 dark:text-teal-100">{visible.length} turnos</span></div>
 {periodView==='month'&&<div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700"><div className="min-w-[720px]"><div className="grid grid-cols-7 bg-slate-50 text-center text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-700/80 dark:text-slate-200">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=><div key={x} className="p-2.5">{x}</div>)}</div><div className="grid grid-cols-7">{calendarDays.map(d=>{const scheduled=items.filter(x=>sameDay(localDate(x.fecha),d)).sort((a,b)=>String(a.hora_inicio).localeCompare(String(b.hora_inicio))),isToday=sameDay(d,new Date()),isSelected=sameDay(d,anchorDate),outside=d.getMonth()!==anchorDate.getMonth();return <button key={d.toISOString()} onClick={()=>{setAnchorDate(d);setPeriodView('day')}} className={`min-h-28 border-t border-r border-slate-100 p-2 text-left text-xs transition hover:bg-teal-50/70 dark:border-slate-700 dark:hover:bg-teal-900/30 ${outside?'bg-slate-50/60 text-slate-300 dark:bg-slate-900/30 dark:text-slate-500':isSelected?'bg-teal-50 dark:bg-teal-900/30':''}`}><span className={`grid size-7 place-items-center rounded-full font-bold ${isToday?'bg-teal-600 text-white':isSelected?'ring-2 ring-teal-500':''}`}>{d.getDate()}</span><span className="mt-1.5 block space-y-1">{scheduled.slice(0,3).map(x=>{const color=x.tipo_turno==='Noche'?config.turno_noche_color:x.tipo_turno==='Dia'?config.turno_dia_color:config.turno_personalizado_color;return <span key={x.id} style={{backgroundColor:`${color}18`,borderColor:color,color}} className="block truncate rounded-md border-l-4 px-1.5 py-1 text-[10px] font-bold"><span className="mr-1 opacity-75">{x.hora_inicio}</span>{x.guardia_nombre}</span>})}{scheduled.length>3&&<span className="block pl-1 text-[9px] font-semibold text-slate-500 dark:text-slate-300">+{scheduled.length-3} turnos</span>}</span></button>})}</div></div></div>}</section>
 <WeeklyGrid active={periodView==='week'} guardias={guardias} items={items} days={weekDays} config={config} onCreate={beginAt} onEdit={begin} canEdit={canEdit}/>
 <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(x=>{const color=x.tipo_turno==='Noche'?config.turno_noche_color:x.tipo_turno==='Dia'?config.turno_dia_color:config.turno_personalizado_color;return <article key={x.id} style={{borderColor:color,backgroundColor:`${color}12`}} className="rounded-xl border p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><b className="block truncate text-sm">{x.guardia_nombre}</b><p className="mt-0.5 text-xs text-slate-500">{new Date(x.fecha).toLocaleDateString('es-CL')} · {x.hora_inicio}–{x.hora_fin}</p></div><Badge tone={toneFor(x.estado)}>{x.estado}</Badge></div><p className="mt-2 truncate text-xs font-semibold" style={{color}}>{x.tipo_turno} · {x.recinto_nombre||x.ubicacion||'Sin ubicación'}</p>{(canEdit||canDelete)&&<div className="mt-3 flex gap-2 border-t border-current/10 pt-2">{canEdit&&<button onClick={()=>begin(x)} className="inline-flex flex-1 items-center justify-center gap-1 rounded-lg bg-white/70 px-2 py-1.5 text-xs font-semibold dark:bg-slate-900/50"><Pencil size={13}/>Editar</button>}{canDelete&&<button className="rounded-lg p-1.5 text-red-600 hover:bg-red-50" onClick={async()=>{if(confirm('¿Eliminar este turno?')){await api('/turno/'+x.id,{method:'DELETE'});load()}}}><Trash2 size={14}/></button>}</div>}</article>})}</div>{!visible.length&&<div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-500">No hay turnos en este período.</div>}
 <Dialog open={open} onClose={()=>setOpen(false)} title={editing?'Modificar turno':'Programar turnos'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Select label="Guardia" value={v.guardia_nombre} set={(x:string)=>setV({...v,guardia_nombre:x})} options={guardias.map(x=>x.nombre)} required/><Select label="Recinto" value={v.recinto_nombre} set={(x:string)=>setV({...v,recinto_nombre:x})} options={recintos.map(x=>x.nombre)}/><Select label="Jornada" value={v.tipo_turno} set={applyType} options={['Manana','Tarde','Dia','Noche','Personalizado']}/>{!editing&&<Select label="Programar por" value={v.periodo} set={(x:string)=>setV({...v,periodo:x})} options={['dia','semana']}/>}<p className="sm:col-span-2 rounded-lg bg-teal-50 p-3 text-xs text-teal-800 dark:bg-teal-950 dark:text-teal-200">El horario sugerido siempre se puede modificar antes de guardar.</p><Field label={v.periodo==='semana'?'Fecha de la semana':'Fecha'} type="date" value={v.fecha} set={(x:string)=>setV({...v,fecha:x})} required/>{!editing&&v.periodo==='semana'&&<div className="sm:col-span-2 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><p className="mb-3 text-sm font-bold">Días de trabajo</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{workDays.map(([day,label])=><label key={day} className={`flex cursor-pointer items-center gap-2 rounded-lg border p-2 text-sm ${selectedDays.includes(day)?'border-teal-500 bg-teal-50 dark:bg-teal-950/40':'border-slate-200 dark:border-slate-700'}`}><input type="checkbox" checked={selectedDays.includes(day)} onChange={()=>toggleDay(day)}/>{label}</label>)}</div><div className={`mt-3 rounded-lg p-3 text-sm ${weeklyHours>45?'bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-200':'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-200'}`}><b>{selectedDays.length} días × {hoursPerShift.toFixed(1)} horas = {weeklyHours.toFixed(1)} horas semanales</b><span className="mt-1 block text-xs">{7-selectedDays.length} día(s) de descanso{weeklyHours>45?' · Supera el máximo semanal de 45 horas.':''}</span></div></div>}<Field label="Hora inicio" type="time" value={v.hora_inicio} set={(x:string)=>setV({...v,hora_inicio:x})} required/><Field label="Hora término" type="time" value={v.hora_fin} set={(x:string)=>setV({...v,hora_fin:x})} required/><Field label="Ubicación" value={v.ubicacion} set={(x:string)=>setV({...v,ubicacion:x})}/><label className="sm:col-span-2 text-sm font-semibold">Observaciones<textarea value={v.observaciones||''} onChange={e=>setV({...v,observaciones:e.target.value})} className="mt-1.5 w-full rounded-xl border bg-transparent p-3 dark:border-slate-700"/></label>{editing&&<Select label="Estado" value={v.estado} set={(x:string)=>setV({...v,estado:x})} options={['Programado','En_curso','Completado','Cancelado']}/>} {error&&<p className="sm:col-span-2 text-red-600">{error}</p>}<Button className="sm:col-span-2">{editing?'Guardar modificación':'Crear programación'}</Button></form></Dialog></>}
function Field({label,value,set,type='text',required=false}:any){return <label className="text-sm font-semibold">{label}<input type={type} value={value||''} onChange={e=>set(e.target.value)} required={required} className="mt-1.5 w-full rounded-xl border bg-transparent p-2.5 dark:border-slate-700"/></label>}
function Select({label,value,set,options,required=false}:any){useEffect(()=>{if(!value&&options.length>0)set(options[0])},[value,options.length]);const display=(x:string)=>x==='Manana'?'Mañana':x==='Dia'?'Día':x==='dia'?'Un día':x==='semana'?'Una semana':x==='mes'?'Un mes':x.replaceAll('_',' ');return <label className="text-sm font-semibold">{label}<select value={value||''} onChange={e=>set(e.target.value)} required={required} className="mt-1.5 w-full rounded-xl border bg-white p-2.5 dark:border-slate-700 dark:bg-slate-900">{!value&&<option value="">Seleccione...</option>}{options.map((x:string)=><option key={x} value={x}>{display(x)}</option>)}</select></label>}
