import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { db } from './lib.js';
import { admin, asyncHandler, auth } from './middleware.js';

export const databaseAdmin = Router();
const backupSchema=z.object({format:z.literal('guardiapro-backup'),version:z.literal(1),data:z.object({recintos:z.array(z.record(z.any())),guardias:z.array(z.record(z.any())),turnos:z.array(z.record(z.any())),rondas:z.array(z.record(z.any())),entradas:z.array(z.record(z.any())),reportes:z.array(z.record(z.any())),alertas:z.array(z.record(z.any())),relevos:z.array(z.record(z.any())).optional().default([]),configuracion:z.record(z.any()).nullable().optional()})});
const recintoRowsSchema=z.array(z.object({nombre:z.string().trim().min(1),direccion:z.string().trim().min(1),tipo:z.string().trim().min(1),estado:z.enum(['Activo','Inactivo']).default('Activo')}).passthrough());
const recintosBackupSchema=z.union([z.object({format:z.literal('guardiapro-recintos-backup'),version:z.literal(1),data:z.object({recintos:recintoRowsSchema})}),recintoRowsSchema]);
const userRowSchema=z.object({id:z.string().min(1),full_name:z.string().min(1),email:z.string().email(),password:z.string().nullable(),role:z.enum(['admin','jefe_turno','guardia']),rango:z.enum(['supervisor','guardia_senior','guardia','cabo','conserje','nochero']).nullable(),telefono:z.string().nullable(),cargo:z.string().nullable(),permisos:z.record(z.any()),guardia_id:z.string().nullable(),foto_url:z.string().nullable(),must_change_password:z.boolean(),email_verified:z.boolean(),google_id:z.string().nullable(),enabled:z.boolean(),created_at:z.coerce.date(),updated_at:z.coerce.date()});
const usersBackupSchema=z.object({format:z.literal('guardiapro-users-backup'),version:z.literal(1),data:z.object({users:z.array(userRowSchema)})});
const configurationFields=['permitir_registro_publico','smtp_host','smtp_port','smtp_secure','smtp_user','mail_from','telegram_enabled','telegram_chat_id','theme','brand_name','brand_subtitle','hero_title','hero_description','hero_footer','logo_url','icon_url','hero_image_url','public_page_enabled','public_banner_color','company_contact_enabled','company_contact_name','company_email','company_phone','company_address','company_website_url','company_title','company_description','company_services','quote_email'] as const;
const dateFields:Record<string,string[]>={recintos:['created_at','updated_at'],guardias:['fecha_ingreso','created_at','updated_at'],turnos:['fecha','created_at','updated_at'],rondas:['fecha_hora_inicio','fecha_hora_fin','created_at','updated_at'],entradas:['hora_entrada','hora_salida','created_at','updated_at'],reportes:['fecha','created_at','updated_at'],alertas:['fecha','created_at','updated_at'],relevos:['fecha_hora','created_at','updated_at']};
function rowsForImport(name:string,rows:Record<string,any>[],userIds:Set<string>){return rows.map(row=>{const value={...row};for(const field of dateFields[name]||[])if(value[field])value[field]=new Date(value[field]);if('created_by_id'in value&&!userIds.has(value.created_by_id))value.created_by_id=null;return value})}
async function clearOperationalData(tx:any){await tx.relevo.deleteMany();await tx.alerta.deleteMany();await tx.reporte.deleteMany();await tx.entrada.deleteMany();await tx.ronda.deleteMany();await tx.turno.deleteMany();await tx.guardia.deleteMany();await tx.recinto.deleteMany()}

databaseAdmin.get('/export',auth,admin,asyncHandler(async(_req,res)=>{const[recintos,guardias,turnos,rondas,entradas,reportes,alertas,relevos,config]=await Promise.all([db.recinto.findMany(),db.guardia.findMany(),db.turno.findMany(),db.ronda.findMany(),db.entrada.findMany(),db.reporte.findMany(),db.alerta.findMany(),db.relevo.findMany(),db.configuracion.findUnique({where:{id:1}})]);const configuracion=config?Object.fromEntries(configurationFields.map(key=>[key,config[key]])):null;res.setHeader('Content-Disposition',`attachment; filename="guardiapro-${new Date().toISOString().slice(0,10)}.json"`);res.json({format:'guardiapro-backup',version:1,exported_at:new Date().toISOString(),data:{recintos,guardias,turnos,rondas,entradas,reportes,alertas,relevos,configuracion}})}));
databaseAdmin.post('/clear',auth,admin,asyncHandler(async(req,res)=>{const{password}=z.object({password:z.string().min(1)}).parse(req.body);const user=await db.user.findUnique({where:{id:req.user!.id}});if(!user?.password||!await bcrypt.compare(password,user.password))return res.status(401).json({message:'Contraseña incorrecta'});await db.$transaction(clearOperationalData);res.json({message:'Base de datos operativa limpiada. Los usuarios y la configuración se conservaron.'})}));
databaseAdmin.post('/import',auth,admin,asyncHandler(async(req,res)=>{const backup=backupSchema.parse(req.body);const userIds=new Set((await db.user.findMany({select:{id:true}})).map(user=>user.id));await db.$transaction(async tx=>{await clearOperationalData(tx);const d=backup.data;if(d.recintos.length)await tx.recinto.createMany({data:rowsForImport('recintos',d.recintos,userIds) as any});if(d.guardias.length)await tx.guardia.createMany({data:rowsForImport('guardias',d.guardias,userIds) as any});if(d.turnos.length)await tx.turno.createMany({data:rowsForImport('turnos',d.turnos,userIds) as any});if(d.rondas.length)await tx.ronda.createMany({data:rowsForImport('rondas',d.rondas,userIds) as any});if(d.entradas.length)await tx.entrada.createMany({data:rowsForImport('entradas',d.entradas,userIds) as any});if(d.reportes.length)await tx.reporte.createMany({data:rowsForImport('reportes',d.reportes,userIds) as any});if(d.alertas.length)await tx.alerta.createMany({data:rowsForImport('alertas',d.alertas,userIds) as any});if(d.relevos.length)await tx.relevo.createMany({data:rowsForImport('relevos',d.relevos,userIds) as any});if(d.configuracion){const config=Object.fromEntries(Object.entries(d.configuracion).filter(([key])=>(configurationFields as readonly string[]).includes(key)));await tx.configuracion.upsert({where:{id:1},update:config,create:{id:1,...config}})}});res.json({message:'Base de datos importada correctamente. Los usuarios existentes se conservaron.'})}));

databaseAdmin.get('/recintos/export',auth,admin,asyncHandler(async(_req,res)=>{const recintos=await db.recinto.findMany();res.setHeader('Content-Disposition',`attachment; filename="guardiapro-recintos-${new Date().toISOString().slice(0,10)}.json"`);res.json({format:'guardiapro-recintos-backup',version:1,exported_at:new Date().toISOString(),data:{recintos}})}));
databaseAdmin.post('/recintos/import',auth,admin,asyncHandler(async(req,res)=>{const backup=recintosBackupSchema.parse(req.body);const recintoRows=Array.isArray(backup)?backup:backup.data.recintos;const userIds=new Set((await db.user.findMany({select:{id:true}})).map(user=>user.id));const relatedModels=['guardia','turno','ronda','entrada','reporte','alerta'] as const;await db.$transaction(async tx=>{const references:Record<string,Array<{id:string;recinto_id:string|null}>>={};for(const model of relatedModels)references[model]=await(tx as any)[model].findMany({where:{recinto_id:{not:null}},select:{id:true,recinto_id:true}});await tx.recinto.deleteMany();const rows=rowsForImport('recintos',recintoRows,userIds);if(rows.length)await tx.recinto.createMany({data:rows as any});const importedIds=new Set(rows.map(row=>String(row.id)));for(const model of relatedModels)for(const item of references[model])if(item.recinto_id&&importedIds.has(item.recinto_id))await(tx as any)[model].update({where:{id:item.id},data:{recinto_id:item.recinto_id}})});res.json({message:'Recintos importados correctamente. Las asignaciones coincidentes se conservaron.'})}));

databaseAdmin.get('/users/export',auth,admin,asyncHandler(async(_req,res)=>{const users=await db.user.findMany();res.setHeader('Content-Disposition',`attachment; filename="guardiapro-users-${new Date().toISOString().slice(0,10)}.json"`);res.json({format:'guardiapro-users-backup',version:1,exported_at:new Date().toISOString(),data:{users}})}));
databaseAdmin.post('/users/import',auth,admin,asyncHandler(async(req,res)=>{const {data}=usersBackupSchema.parse(req.body);const guardiaIds=new Set((await db.guardia.findMany({select:{id:true}})).map(guardia=>guardia.id));await db.$transaction(async tx=>{for(const row of data.users){const emailOwner=await tx.user.findUnique({where:{email:row.email},select:{id:true}});if(emailOwner&&emailOwner.id!==row.id)throw new Error(`El correo ${row.email} pertenece a otro usuario existente`);const value={...row,guardia_id:row.guardia_id&&guardiaIds.has(row.guardia_id)?row.guardia_id:null};await tx.user.upsert({where:{id:row.id},update:value,create:value})}});res.json({message:`Usuarios importados correctamente: ${data.users.length} cuenta(s) agregadas o actualizadas. Las cuentas no incluidas se conservaron.`})}));
