import { Image, Palette, Trash2, UploadCloud } from 'lucide-react';

const themes=[['esmeralda','Esmeralda','#0d9488'],['oceano','Océano','#2563eb'],['borgona','Borgoña','#be123c'],['arena','Arena','#b45309'],['grafito','Grafito','#374151']];
const field='mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 dark:border-slate-700';

export default function BrandingSettings({v,setV}:{v:any;setV:(x:any)=>void}){
  const change=(name:string,value:any)=>setV({...v,[name]:value});
  const upload=(name:string,file?:File)=>{if(!file)return;if(file.size>2_000_000)return alert('La imagen no puede superar 2 MB');const reader=new FileReader();reader.onload=()=>change(name,reader.result);reader.readAsDataURL(file)};
  return <>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <div className="mb-5 flex items-center gap-2"><Palette className="text-teal-600"/><div><h2 className="text-lg font-bold">Tema e identidad visual</h2><p className="text-sm text-slate-500">Personaliza los colores y la marca visible en toda la plataforma.</p></div></div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{themes.map(([id,label,color])=><button type="button" key={id} onClick={()=>change('theme',id)} className={`rounded-xl border-2 p-3 text-left ${v.theme===id?'border-slate-900 dark:border-white':'border-transparent bg-slate-50 dark:bg-slate-950'}`}><span className="mb-2 block h-8 rounded-lg" style={{backgroundColor:color}}/><b className="text-sm">{label}</b></button>)}</div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><Text label="Nombre de marca" name="brand_name" v={v} change={change}/><Text label="Subtítulo" name="brand_subtitle" v={v} change={change}/><Text label="Título principal" name="hero_title" v={v} change={change}/><Text label="Frase final" name="hero_footer" v={v} change={change}/><label className="text-sm font-semibold sm:col-span-2">Descripción principal<textarea rows={3} value={v.hero_description||''} onChange={e=>change('hero_description',e.target.value)} className={field}/></label></div>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <div className="mb-5 flex items-center gap-2"><Image className="text-purple-600"/><div><h2 className="text-lg font-bold">Imágenes corporativas</h2><p className="text-sm text-slate-500">PNG, JPG, WebP o SVG; máximo 2 MB por imagen. La vista conserva la proporción y no deforma el archivo.</p></div></div>
      <div className="grid items-start gap-4 lg:grid-cols-3">
        <Upload label="Logo" help="Recomendado: 800 × 300 px" ratio="aspect-[8/3]" value={v.logo_url} onFile={(f:File)=>upload('logo_url',f)} clear={()=>change('logo_url',null)}/>
        <Upload label="Icono de barra lateral y sitio" help="Se muestra junto al nombre de marca. Recomendado: 512 × 512 px" ratio="aspect-square" value={v.icon_url} onFile={(f:File)=>upload('icon_url',f)} clear={()=>change('icon_url',null)}/>
        <Upload label="Imagen principal" help="Recomendado: 1600 × 900 px" ratio="aspect-video" value={v.hero_image_url} onFile={(f:File)=>upload('hero_image_url',f)} clear={()=>change('hero_image_url',null)}/>
      </div>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">Página pública para clientes</h2><label className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><input type="checkbox" checked={!!v.public_page_enabled} onChange={e=>change('public_page_enabled',e.target.checked)}/><span><b>Publicar página de empresa</b><small className="block text-slate-500">Disponible en la dirección principal y en /empresa.</small></span></label><label className="mt-5 block text-sm font-semibold">Color del banner de clientes<div className="mt-2 flex items-center gap-3"><input type="color" value={v.public_banner_color||'#e2e8f0'} onChange={e=>change('public_banner_color',e.target.value)} className="h-11 w-16 cursor-pointer rounded-lg border border-slate-200 bg-white p-1"/><input value={v.public_banner_color||'#e2e8f0'} onChange={e=>change('public_banner_color',e.target.value)} pattern="#[0-9a-fA-F]{6}" className="w-36 rounded-xl border border-slate-200 bg-transparent p-2.5 font-mono dark:border-slate-700"/><span className="text-xs font-normal text-slate-500">Usa un color claro para logos negros.</span></div></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><Text label="Título de empresa" name="company_title" v={v} change={change}/><Text label="Email que recibe cotizaciones" name="quote_email" type="email" v={v} change={change}/><label className="text-sm font-semibold sm:col-span-2">Información de la empresa<textarea rows={4} value={v.company_description||''} onChange={e=>change('company_description',e.target.value)} className={field}/></label><label className="text-sm font-semibold sm:col-span-2">Servicios (uno por línea)<textarea rows={5} value={v.company_services||''} onChange={e=>change('company_services',e.target.value)} className={field}/></label></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">Datos de contacto de la empresa</h2><label className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><input type="checkbox" checked={!!v.company_contact_enabled} onChange={e=>change('company_contact_enabled',e.target.checked)}/><span><b>Mostrar datos de contacto</b><small className="block text-slate-500">Activa o desactiva el bloque completo en la página de clientes.</small></span></label>{v.company_contact_enabled&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><Text label="Nombre de contacto" name="company_contact_name" v={v} change={change}/><Text label="Correo de la empresa" name="company_email" type="email" v={v} change={change}/><Text label="Número celular" name="company_phone" type="tel" v={v} change={change}/><Text label="URL de la página" name="company_website_url" type="url" v={v} change={change}/><label className="text-sm font-semibold sm:col-span-2">Dirección<input value={v.company_address||''} onChange={e=>change('company_address',e.target.value)} className={field}/></label></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">Turnos, fecha y hora</h2><p className="mt-1 text-sm text-slate-500">Define horarios y colores para distinguir claramente cada jornada.</p><label className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><input type="checkbox" checked={!!v.shift_email_enabled} onChange={e=>change('shift_email_enabled',e.target.checked)}/><span><b>Enviar programación por correo al guardia</b><small className="block text-slate-500">Requiere email del guardia y SMTP configurado.</small></span></label><div className="mt-5 grid gap-4 sm:grid-cols-3"><Text label="Zona horaria" name="timezone" v={v} change={change}/><Text label="Formato de fecha" name="date_format" v={v} change={change}/><Text label="Formato de hora" name="time_format" v={v} change={change}/></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><ShiftStyle title="Turno de día" colorName="turno_dia_color" startName="turno_dia_inicio" endName="turno_dia_fin" v={v} change={change}/><ShiftStyle title="Turno de noche" colorName="turno_noche_color" startName="turno_noche_inicio" endName="turno_noche_fin" v={v} change={change}/><div className="rounded-xl border p-4 dark:border-slate-700"><h3 className="mb-3 font-bold">Turno personalizado</h3><Color label="Color" name="turno_personalizado_color" v={v} change={change}/><p className="mt-3 text-xs text-slate-500">El horario se define al crear cada turno.</p></div></div></section>
  </>;
}

function Text({label,name,v,change,type='text'}:any){return <label className="text-sm font-semibold">{label}<input type={type} value={v[name]||''} onChange={e=>change(name,e.target.value)} className={field}/></label>}
function Color({label,name,v,change}:any){return <label className="text-sm font-semibold">{label}<div className="mt-1.5 flex items-center gap-2"><input type="color" value={v[name]||'#64748b'} onChange={e=>change(name,e.target.value)} className="h-10 w-14 cursor-pointer rounded border p-1"/><input value={v[name]||''} onChange={e=>change(name,e.target.value)} pattern="#[0-9a-fA-F]{6}" className={field+' mt-0'}/></div></label>}
function ShiftStyle({title,colorName,startName,endName,v,change}:any){return <div className="rounded-xl border p-4 dark:border-slate-700"><h3 className="mb-3 font-bold">{title}</h3><div className="space-y-3"><Color label="Color" name={colorName} v={v} change={change}/><Text label="Hora de inicio" name={startName} type="time" v={v} change={change}/><Text label="Hora de término" name={endName} type="time" v={v} change={change}/></div></div>}

function Upload({label,help,ratio,value,onFile,clear}:any){return <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div><b className="text-sm">{label}</b><p className="mt-0.5 text-xs text-slate-500">{help}</p></div><label className={`group my-3 grid w-full cursor-pointer place-items-center overflow-hidden rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 transition hover:border-purple-500 hover:bg-purple-50 dark:border-slate-700 dark:bg-slate-950 dark:hover:border-purple-500 ${ratio}`}>{value?<img src={value} alt={`Vista previa de ${label}`} className="h-full w-full object-contain p-2"/>:<span className="flex flex-col items-center gap-2 px-4 text-center text-slate-500 group-hover:text-purple-600"><UploadCloud size={32}/><span className="text-sm font-semibold">Subir imagen</span><span className="text-xs">Haz clic para seleccionar</span></span>}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>onFile(e.target.files?.[0])} className="sr-only"/></label>{value&&<button type="button" onClick={clear} className="inline-flex items-center gap-1.5 text-xs font-semibold text-red-600 hover:text-red-700"><Trash2 size={14}/>Quitar imagen</button>}</div>}
