import{useEffect,useMemo,useState}from'react';import{api}from'../state';import{modules}from'../config';import{Badge,Button,Dialog,EntityForm,PageHead,Pencil,Plus,Search,Trash2,toneFor}from'../components';
export default function CrudPage({moduleKey}:{moduleKey:string}){
 const m=modules[moduleKey];const[items,setItems]=useState<any[]>([]);const[recintos,setRecintos]=useState<any[]>([]);const[guardias,setGuardias]=useState<any[]>([]);const[q,setQ]=useState('');const[editing,setEditing]=useState<any>();const[open,setOpen]=useState(false);const[error,setError]=useState('');
 const fields=useMemo(()=>m.fields.map(f=>f.name==='recinto_nombre'?{...f,options:recintos.map(r=>r.nombre)}:f.name==='guardia_nombre'?{...f,options:guardias.map(g=>g.nombre)}:f),[m,recintos,guardias]);
 const load=()=>api(`/${m.key}?q=${encodeURIComponent(q)}`).then(r=>setItems(r.data)).catch(e=>setError(e.message));
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[moduleKey,q]);
 useEffect(()=>{if(['guardia','reporte'].includes(m.key))api('/lookups/recintos').then(setRecintos);if(m.key==='reporte')api('/lookups/guardias').then(setGuardias)},[moduleKey]);
 const save=async(v:any)=>{const data={...v};if(m.key==='guardia'){const recinto=recintos.find(r=>r.nombre===(data.recinto_nombre||recintos[0]?.nombre));data.recinto_id=recinto?.id||null;data.recinto_nombre=recinto?.nombre||null}if(m.key==='reporte'){const guardia=guardias.find(g=>g.nombre===(data.guardia_nombre||guardias[0]?.nombre));const recinto=recintos.find(r=>r.nombre===(data.recinto_nombre||recintos[0]?.nombre));data.guardia_id=guardia?.id||null;data.guardia_nombre=guardia?.nombre||null;data.recinto_id=recinto?.id||null;data.recinto_nombre=recinto?.nombre||null}await api(`/${m.key}${editing?'/'+editing.id:''}`,{method:editing?'PUT':'POST',body:JSON.stringify(data)});setOpen(false);setEditing(undefined);load()};
 const del=async(x:any)=>{if(!confirm(`¿Eliminar ${m.singular} “${x[m.primary]}”? Esta acción no se puede deshacer.`))return;await api(`/${m.key}/${x.id}`,{method:'DELETE'});load()};
 return <><PageHead title={m.title} subtitle={m.subtitle} action={<Button onClick={()=>{setEditing(undefined);setOpen(true)}}><Plus size={18}/>Nuevo {m.singular}</Button>}/><div className="relative mb-5 max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Buscar en ${m.title.toLowerCase()}…`} className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 dark:border-slate-700 dark:bg-slate-900"/></div>{error&&<p className="mb-4 text-red-600">{error}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(x=><article key={x.id} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{x[m.primary]}</h3><p className="mt-1 truncate text-sm text-slate-500">{x[m.secondary!]||'Sin información adicional'}</p>{x.guardia_nombre&&<p className="mt-2 text-xs font-semibold">{x.guardia_nombre}</p>}{x.recinto_nombre&&<p className="mt-1 text-xs font-semibold text-teal-700">{x.recinto_nombre}</p>}</div>{m.status&&<Badge tone={toneFor(x[m.status])}>{x[m.status]}</Badge>}</div><div className="mt-5 flex gap-2 border-t border-slate-100 pt-4 dark:border-slate-800"><Button variant="secondary" className="flex-1" onClick={()=>{setEditing(x);setOpen(true)}}><Pencil size={16}/>Editar</Button><button onClick={()=>del(x)} className="rounded-xl p-2.5 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={18}/></button></div></article>)}</div>{!items.length&&!error&&<div className="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-slate-500">No hay registros. Crea el primero para comenzar.</div>}<Dialog open={open} onClose={()=>setOpen(false)} title={`${editing?'Editar':'Nuevo'} ${m.singular}`}><EntityForm fields={fields} initial={editing} onSave={save} onCancel={()=>setOpen(false)}/>{m.key==='guardia'&&!recintos.length&&<p className="mt-3 text-sm text-amber-600">Primero debes crear un recinto activo.</p>}{m.key==='reporte'&&(!recintos.length||!guardias.length)&&<p className="mt-3 text-sm text-amber-600">Debes tener al menos un guardia y un recinto activos.</p>}</Dialog></>
}
