import { useState } from 'react';
import { Camera, Trash2, UploadCloud } from 'lucide-react';
import { api,useAuth } from '../state';
import { Button,PageHead } from '../components';

export default function Profile(){
  const {user,refresh,logout}=useAuth();
  const [v,setV]=useState<any>({...user,password:'',current_password:'',foto_url:user?.foto_url||null});
  const [msg,setMsg]=useState('');const [error,setError]=useState('');
  const upload=(file?:File)=>{if(!file)return;if(file.size>2_000_000)return setError('La fotografía no puede superar 2 MB');if(!file.type.startsWith('image/'))return setError('Selecciona una imagen PNG, JPG o WebP');const reader=new FileReader();reader.onload=()=>setV({...v,foto_url:String(reader.result)});reader.readAsDataURL(file)};
  const save=async(event:any)=>{event.preventDefault();setMsg('');setError('');try{const body={full_name:v.full_name,telefono:v.telefono,cargo:v.cargo,foto_url:v.foto_url,...(v.password?{password:v.password,current_password:v.current_password}:{})};await api('/profile',{method:'PUT',body:JSON.stringify(body)});setMsg('Perfil actualizado correctamente');setV({...v,password:'',current_password:''});await refresh()}catch(reason){setError((reason as Error).message)}};
  return <><PageHead title="Mi Perfil" subtitle="Datos personales, fotografía y seguridad de tu cuenta"/>
    {user?.must_change_password&&<div className="mb-5 max-w-2xl rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-800"><b>Debes cambiar tu contraseña temporal.</b><p className="mt-1">Ingresa la contraseña recibida como contraseña actual y define una nueva para continuar.</p></div>}
    <form onSubmit={save} className="max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <section className="mb-6"><h2 className="mb-3 flex items-center gap-2 font-bold"><Camera size={18} className="text-teal-600"/>Fotografía de perfil</h2><label className="group grid min-h-44 cursor-pointer place-items-center overflow-hidden rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 hover:border-teal-500 dark:border-slate-700 dark:bg-slate-950">{v.foto_url?<img src={v.foto_url} alt="Fotografía de perfil" className="size-40 rounded-full object-cover p-1"/>:<span className="flex flex-col items-center gap-2 text-slate-500 group-hover:text-teal-600"><UploadCloud size={32}/><b className="text-sm">Subir fotografía</b><span className="text-xs">PNG, JPG o WebP · máximo 2 MB</span></span>}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>upload(event.target.files?.[0])}/></label>{v.foto_url&&<button type="button" onClick={()=>setV({...v,foto_url:null})} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-red-600"><Trash2 size={14}/>Quitar fotografía</button>}</section>
      <div className="grid gap-4 sm:grid-cols-2">{([['full_name','Nombre completo','text'],['email','Correo electrónico','email'],['telefono','Teléfono','text'],['cargo','Cargo','text'],['current_password',user?.must_change_password?'Contraseña temporal':'Contraseña actual','password'],['password','Nueva contraseña','password']] as const).map(([name,label,type])=><label key={name} className="text-sm font-semibold">{label}<input type={type} disabled={name==='email'} minLength={type==='password'?8:undefined} required={user?.must_change_password&&['current_password','password'].includes(name)} value={v[name]||''} onChange={event=>setV({...v,[name]:event.target.value})} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 disabled:bg-slate-100 dark:border-slate-700 dark:disabled:bg-slate-800"/></label>)}</div>
      {error&&<p className="mt-4 text-sm text-red-600">{error}</p>}{msg&&<p className="mt-4 text-sm text-emerald-600">{msg}</p>}<Button className="mt-6">Guardar perfil</Button>
      {!user?.must_change_password&&<div className="mt-8 border-t border-slate-200 pt-6 dark:border-slate-800"><h3 className="font-bold text-red-600">Eliminar cuenta</h3><p className="my-3 text-sm text-slate-500">Esta acción es permanente y eliminará tu acceso.</p><Button type="button" variant="danger" onClick={async()=>{if(confirm('¿Confirmas que deseas eliminar permanentemente tu cuenta?')){await api('/profile',{method:'DELETE'});logout()}}}>Eliminar mi cuenta</Button></div>}
    </form>
  </>;
}
