import{useEffect,useMemo,useState}from'react';import{CalendarDays,CalendarRange,ChevronLeft,ChevronRight,List,LogIn,LogOut,Plus,Sun}from'lucide-react';import{api}from'../state';import{Badge,Button,Dialog,PageHead}from'../components';
type View='day'|'week'|'month'|'list';
const nowLocal=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};
const startDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const weekStart=(d:Date)=>addDays(startDay(d),-((d.getDay()+6)%7));
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
export default function Relevos(){
 const[items,setItems]=useState<any[]>([]),[guardias,setGuardias]=useState<any[]>([]),[recintos,setRecintos]=useState<any[]>([]),[open,setOpen]=useState(false),[error,setError]=useState('');
 const[v,setV]=useState<any>({fecha_hora:nowLocal(),estado_entrega:'Completa',novedades:''}),[view,setView]=useState<View>('week'),[anchor,setAnchor]=useState(()=>startDay(new Date()));
 const load=()=>api('/relevo?limit=500').then(x=>setItems(x.data));useEffect(()=>{load();api('/lookups/guardias').then(setGuardias);api('/lookups/recintos').then(setRecintos)},[]);
 const range=useMemo(()=>{if(view==='list')return null;if(view==='day')return{start:startDay(anchor),end:addDays(startDay(anchor),1)};if(view==='week'){const start=weekStart(anchor);return{start,end:addDays(start,7)}}return{start:new Date(anchor.getFullYear(),anchor.getMonth(),1),end:new Date(anchor.getFullYear(),anchor.getMonth()+1,1)}},[view,anchor]);
 const visible=useMemo(()=>items.filter(x=>!range||((d=>!Number.isNaN(d.getTime())&&d>=range.start&&d<range.end)(new Date(x.fecha_hora)))),[items,range]);
 const label=view==='list'?'Todos los cambios de turno':view==='day'?anchor.toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'}):view==='week'?`${range!.start.toLocaleDateString('es-CL',{day:'numeric',month:'short'})} – ${addDays(range!.end,-1).toLocaleDateString('es-CL',{day:'numeric',month:'short',year:'numeric'})}`:anchor.toLocaleDateString('es-CL',{month:'long',year:'numeric'});
 const move=(n:number)=>setAnchor(d=>view==='day'?addDays(d,n):view==='week'?addDays(d,n*7):new Date(d.getFullYear(),d.getMonth()+n,1));
 const monthStart=new Date(anchor.getFullYear(),anchor.getMonth(),1),calendarStart=addDays(monthStart,-((monthStart.getDay()+6)%7)),days=Array.from({length:42},(_,i)=>addDays(calendarStart,i));
 const save=async(e:any)=>{e.preventDefault();setError('');try{const out=guardias.find(x=>x.nombre===v.guardia_saliente_nombre),into=guardias.find(x=>x.nombre===v.guardia_entrante_nombre),r=recintos.find(x=>x.nombre===v.recinto_nombre);if(!out||!into)throw new Error('Selecciona el guardia saliente y el guardia entrante');const localDate=new Date(v.fecha_hora);if(Number.isNaN(localDate.getTime()))throw new Error('La fecha y hora del relevo no son válidas');await api('/relevo',{method:'POST',body:JSON.stringify({...v,fecha_hora:localDate.toISOString(),guardia_saliente_id:out.id,guardia_entrante_id:into.id,recinto_id:r?.id})});setOpen(false);setV({fecha_hora:nowLocal(),estado_entrega:'Completa',novedades:''});load()}catch(e){setError((e as Error).message)}};
 const views:[[View,string,any],[View,string,any],[View,string,any],[View,string,any]]=[['day','Día',Sun],['week','Semana',CalendarRange],['month','Mes',CalendarDays],['list','Lista',List]];
 return <><PageHead title="Cambio de turno" subtitle="Registro de relevo y entrega de novedades" action={<Button onClick={()=>setOpen(true)}><Plus size={16}/>Registrar relevo</Button>}/>
 <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex w-fit flex-wrap gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-sm dark:border-slate-700 dark:bg-slate-900">{views.map(([x,t,I])=><button key={x} onClick={()=>setView(x)} className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold transition ${view===x?'bg-slate-800 text-white shadow-sm dark:bg-slate-100 dark:text-slate-900':'text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800'}`}><I size={15}/>{t}</button>)}</div><div className="flex items-center gap-1 rounded-xl border border-slate-100 bg-white p-1 dark:border-slate-800 dark:bg-slate-900"><button onClick={()=>move(-1)} disabled={view==='list'} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100 disabled:opacity-30 dark:hover:bg-slate-800"><ChevronLeft size={18}/></button><button onClick={()=>setAnchor(startDay(new Date()))} className="rounded-lg px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800">Hoy</button><button onClick={()=>move(1)} disabled={view==='list'} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100 disabled:opacity-30 dark:hover:bg-slate-800"><ChevronRight size={18}/></button></div></div><div className="mt-3 flex items-center justify-between gap-3"><h2 className="font-bold capitalize text-slate-800 dark:text-slate-100">{label}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{visible.length} relevos</span></div>
 {view==='month'&&<div className="mt-4 overflow-hidden rounded-xl border border-teal-100 bg-white/80 dark:border-teal-900 dark:bg-slate-900/80"><div className="grid grid-cols-7 bg-teal-50 text-center text-[11px] font-bold uppercase text-teal-800 dark:bg-teal-950 dark:text-teal-200">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=><div key={x} className="p-2">{x}</div>)}</div><div className="grid grid-cols-7">{days.map(d=>{const records=items.filter(x=>sameDay(new Date(x.fecha_hora),d));return <button key={d.toISOString()} onClick={()=>{setAnchor(d);setView('day')}} className={`min-h-20 border-r border-t border-slate-100 p-1.5 text-left text-xs hover:bg-teal-50/60 dark:border-slate-800 dark:hover:bg-teal-950/30 ${d.getMonth()!==anchor.getMonth()?'text-slate-300':''}`}><b>{d.getDate()}</b>{records.slice(0,2).map(x=><span key={x.id} className="mt-1 block truncate rounded bg-teal-50 px-1 py-0.5 text-[9px] font-bold text-teal-700">{x.guardia_entrante_nombre}</span>)}{records.length>2&&<span className="text-[9px] text-slate-500">+{records.length-2} más</span>}</button>})}</div></div>}</section>
 <div className="space-y-3">{visible.map(x=><article key={x.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-teal-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-lg bg-orange-50 px-2.5 py-1.5 text-sm font-bold text-orange-800 dark:bg-orange-950/40 dark:text-orange-200"><LogOut size={15}/>Sale: {x.guardia_saliente_nombre}</span><span className="text-slate-300">→</span><span className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-50 px-2.5 py-1.5 text-sm font-bold text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-200"><LogIn size={15}/>Entra: {x.guardia_entrante_nombre}</span></div><Badge tone={x.estado_entrega==='Completa'?'green':'amber'}>{x.estado_entrega}</Badge></div><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500"><span>{new Date(x.fecha_hora).toLocaleString('es-CL')}</span><span>·</span><span>{x.recinto_nombre||'Sin recinto'}</span></div><p className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-700 dark:bg-slate-950 dark:text-slate-200">{x.novedades}</p></article>)}</div>{!visible.length&&<div className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 dark:border-slate-700">No hay cambios de turno en este período.</div>}
 <Dialog open={open} onClose={()=>setOpen(false)} title="Registrar cambio de turno"><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Sel label="Guardia saliente" value={v.guardia_saliente_nombre} set={(x:string)=>setV((current:any)=>({...current,guardia_saliente_nombre:x}))} options={guardias.map(x=>x.nombre)}/><Sel label="Guardia entrante" value={v.guardia_entrante_nombre} set={(x:string)=>setV((current:any)=>({...current,guardia_entrante_nombre:x}))} options={guardias.map(x=>x.nombre)}/><Sel label="Recinto" value={v.recinto_nombre} set={(x:string)=>setV((current:any)=>({...current,recinto_nombre:x}))} options={recintos.map(x=>x.nombre)}/><label className="text-sm font-semibold">Fecha y hora del relevo<input type="datetime-local" value={v.fecha_hora} onChange={e=>setV((current:any)=>({...current,fecha_hora:e.target.value}))} required className="mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 dark:border-slate-700"/></label><Sel label="Estado de entrega" value={v.estado_entrega} set={(x:string)=>setV((current:any)=>({...current,estado_entrega:x}))} options={['Completa','Con_novedades','Pendiente']}/><label className="sm:col-span-2 text-sm font-semibold">Información entregada<textarea value={v.novedades} onChange={e=>setV((current:any)=>({...current,novedades:e.target.value}))} required rows={5} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-3 dark:border-slate-700"/></label>{error&&<p className="sm:col-span-2 text-red-600">{error}</p>}<Button className="sm:col-span-2">Guardar relevo</Button></form></Dialog></>}
function Sel({label,value,set,options}:any){useEffect(()=>{if(!value&&options[0])set(options[0])},[value,options[0]]);return <label className="text-sm font-semibold">{label}<select value={value||options[0]||''} onChange={e=>set(e.target.value)} required className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-2.5 dark:border-slate-700 dark:bg-slate-900">{options.map((x:string)=><option key={x}>{x}</option>)}</select></label>}
