import{useEffect,useMemo,useState}from'react';
import{CalendarDays,CalendarPlus,ChevronLeft,ChevronRight,List,Pencil,Trash2}from'lucide-react';
import{api}from'../state';import{Badge,Button,Dialog,PageHead,toneFor}from'../components';
type PeriodView='day'|'week'|'month'|'list';
const today=()=>new Date().toLocaleDateString('en-CA');
const startOfDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const weekStart=(d:Date)=>addDays(startOfDay(d),-((d.getDay()+6)%7));
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
const blank=()=>({guardia_nombre:'',recinto_nombre:'',tipo_turno:'Dia',periodo:'dia',fecha:today(),hora_inicio:'08:00',hora_fin:'20:00',ubicacion:'',observaciones:'',estado:'Programado'});

export default function Turnos(){
 const[items,setItems]=useState<any[]>([]),[guardias,setGuardias]=useState<any[]>([]),[recintos,setRecintos]=useState<any[]>([]);
 const[config,setConfig]=useState<any>({turno_dia_inicio:'08:00',turno_dia_fin:'20:00',turno_noche_inicio:'20:00',turno_noche_fin:'08:00',turno_dia_color:'#f59e0b',turno_noche_color:'#2563eb',turno_personalizado_color:'#7c3aed'});
 const[v,setV]=useState<any>(blank()),[editing,setEditing]=useState<any>(null),[open,setOpen]=useState(false),[error,setError]=useState('');
 const[periodView,setPeriodView]=useState<PeriodView>('week'),[anchorDate,setAnchorDate]=useState(()=>startOfDay(new Date()));
 const load=()=>api('/turno?limit=500').then(x=>setItems(x.data));
 useEffect(()=>{load();api('/lookups/guardias').then(setGuardias);api('/lookups/recintos').then(setRecintos);api('/config').then(setConfig).catch(()=>{})},[]);
 const range=useMemo(()=>{if(periodView==='list')return null;if(periodView==='day')return{start:startOfDay(anchorDate),end:addDays(startOfDay(anchorDate),1)};if(periodView==='week'){const start=weekStart(anchorDate);return{start,end:addDays(start,7)}}return{start:new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1),end:new Date(anchorDate.getFullYear(),anchorDate.getMonth()+1,1)}},[anchorDate,periodView]);
 const visible=useMemo(()=>items.filter(x=>!range||((d=>!Number.isNaN(d.getTime())&&d>=range.start&&d<range.end)(new Date(x.fecha)))),[items,range]);
 const label=periodView==='list'?'Todos los turnos':periodView==='day'?anchorDate.toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'}):periodView==='week'?`${range!.start.toLocaleDateString('es-CL',{day:'numeric',month:'short'})} – ${addDays(range!.end,-1).toLocaleDateString('es-CL',{day:'numeric',month:'short',year:'numeric'})}`:anchorDate.toLocaleDateString('es-CL',{month:'long',year:'numeric'});
 const move=(n:number)=>setAnchorDate(d=>periodView==='day'?addDays(d,n):periodView==='week'?addDays(d,n*7):new Date(d.getFullYear(),d.getMonth()+n,1));
 const monthStart=new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1),calendarStart=addDays(monthStart,-((monthStart.getDay()+6)%7));
 const calendarDays=Array.from({length:42},(_,i)=>addDays(calendarStart,i));
 const applyType=(type:string)=>setV((x:any)=>({...x,tipo_turno:type,...(type==='Dia'?{hora_inicio:config.turno_dia_inicio,hora_fin:config.turno_dia_fin}:type==='Noche'?{hora_inicio:config.turno_noche_inicio,hora_fin:config.turno_noche_fin}:{})}));
 const begin=(x?:any)=>{setEditing(x||null);setV(x?{...x,fecha:String(x.fecha).slice(0,10),periodo:'dia'}:{...blank(),hora_inicio:config.turno_dia_inicio,hora_fin:config.turno_dia_fin});setOpen(true)};
 const save=async(e:any)=>{e.preventDefault();setError('');try{const g=guardias.find(x=>x.nombre===v.guardia_nombre),r=recintos.find(x=>x.nombre===v.recinto_nombre);const data={...v,guardia_id:g?.id,guardia_nombre:g?.nombre,recinto_id:r?.id||null,recinto_nombre:r?.nombre||null};if(editing)await api('/turno/'+editing.id,{method:'PUT',body:JSON.stringify(data)});else await api('/turnos/programar',{method:'POST',body:JSON.stringify(data)});setOpen(false);await load()}catch(e){setError((e as Error).message)}};
 return <><PageHead title="Turnos" subtitle="Planificación diaria, semanal y mensual" action={<Button onClick={()=>begin()}><CalendarPlus size={16}/>Programar</Button>}/>
 <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{([['day','Día'],['week','Semana'],['month','Mes'],['list','Lista']]as[PeriodView,string][]).map(([x,t])=><button key={x} onClick={()=>setPeriodView(x)} className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold ${periodView===x?'bg-teal-600 text-white':'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-200'}`}>{x==='month'?<CalendarDays size={15}/>:x==='list'?<List size={15}/>:null}{t}</button>)}</div><div className="flex items-center gap-1"><button onClick={()=>move(-1)} disabled={periodView==='list'} className="rounded-lg p-1.5 hover:bg-slate-100 disabled:opacity-30"><ChevronLeft size={18}/></button><button onClick={()=>setAnchorDate(startOfDay(new Date()))} className="rounded-lg px-3 py-1.5 text-sm font-semibold hover:bg-slate-100">Hoy</button><button onClick={()=>move(1)} disabled={periodView==='list'} className="rounded-lg p-1.5 hover:bg-slate-100 disabled:opacity-30"><ChevronRight size={18}/></button></div></div><div className="mt-3 flex justify-between gap-2"><h2 className="font-bold capitalize">{label}</h2><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-700">{visible.length} turnos</span></div>
 {periodView==='month'&&<div className="mt-4 overflow-hidden rounded-xl border dark:border-slate-700"><div className="grid grid-cols-7 bg-slate-50 text-center text-[11px] font-bold uppercase text-slate-500 dark:bg-slate-800">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=><div key={x} className="p-2">{x}</div>)}</div><div className="grid grid-cols-7">{calendarDays.map(d=>{const scheduled=items.filter(x=>sameDay(new Date(x.fecha),d));return <button key={d.toISOString()} onClick={()=>{setAnchorDate(d);setPeriodView('day')}} className={`min-h-20 border-t border-r p-1.5 text-left text-xs dark:border-slate-800 ${d.getMonth()!==anchorDate.getMonth()?'text-slate-300':''}`}><b>{d.getDate()}</b><span className="mt-1 block space-y-1">{scheduled.slice(0,2).map(x=>{const color=x.tipo_turno==='Noche'?config.turno_noche_color:x.tipo_turno==='Dia'?config.turno_dia_color:config.turno_personalizado_color;return <span key={x.id} style={{backgroundColor:`${color}22`,borderColor:color,color}} className="block truncate rounded border px-1 py-0.5 text-[9px] font-bold">{x.guardia_nombre}</span>})}{scheduled.length>2&&<span className="block text-[9px] font-semibold text-slate-500">+{scheduled.length-2} más</span>}</span></button>})}</div></div>}</section>
 <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(x=>{const color=x.tipo_turno==='Noche'?config.turno_noche_color:x.tipo_turno==='Dia'?config.turno_dia_color:config.turno_personalizado_color;return <article key={x.id} style={{borderColor:color,backgroundColor:`${color}12`}} className="rounded-xl border p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><b className="block truncate text-sm">{x.guardia_nombre}</b><p className="mt-0.5 text-xs text-slate-500">{new Date(x.fecha).toLocaleDateString('es-CL')} · {x.hora_inicio}–{x.hora_fin}</p></div><Badge tone={toneFor(x.estado)}>{x.estado}</Badge></div><p className="mt-2 truncate text-xs font-semibold" style={{color}}>{x.tipo_turno} · {x.recinto_nombre||x.ubicacion||'Sin ubicación'}</p><div className="mt-3 flex gap-2 border-t border-current/10 pt-2"><button onClick={()=>begin(x)} className="inline-flex flex-1 items-center justify-center gap-1 rounded-lg bg-white/70 px-2 py-1.5 text-xs font-semibold dark:bg-slate-900/50"><Pencil size={13}/>Editar</button><button className="rounded-lg p-1.5 text-red-600 hover:bg-red-50" onClick={async()=>{if(confirm('¿Eliminar este turno?')){await api('/turno/'+x.id,{method:'DELETE'});load()}}}><Trash2 size={14}/></button></div></article>})}</div>{!visible.length&&<div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-500">No hay turnos en este período.</div>}
 <Dialog open={open} onClose={()=>setOpen(false)} title={editing?'Modificar turno':'Programar turnos'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Select label="Guardia" value={v.guardia_nombre} set={(x:string)=>setV({...v,guardia_nombre:x})} options={guardias.map(x=>x.nombre)} required/><Select label="Recinto" value={v.recinto_nombre} set={(x:string)=>setV({...v,recinto_nombre:x})} options={recintos.map(x=>x.nombre)}/><Select label="Jornada" value={v.tipo_turno} set={applyType} options={['Dia','Noche','Personalizado']}/>{!editing&&<Select label="Programar por" value={v.periodo} set={(x:string)=>setV({...v,periodo:x})} options={['dia','semana','mes']}/>}<Field label="Fecha inicial" type="date" value={v.fecha} set={(x:string)=>setV({...v,fecha:x})} required/><Field label="Hora inicio" type="time" value={v.hora_inicio} set={(x:string)=>setV({...v,hora_inicio:x})} required/><Field label="Hora fin" type="time" value={v.hora_fin} set={(x:string)=>setV({...v,hora_fin:x})} required/><Field label="Ubicación" value={v.ubicacion} set={(x:string)=>setV({...v,ubicacion:x})}/><label className="sm:col-span-2 text-sm font-semibold">Observaciones<textarea value={v.observaciones||''} onChange={e=>setV({...v,observaciones:e.target.value})} className="mt-1.5 w-full rounded-xl border bg-transparent p-3 dark:border-slate-700"/></label>{editing&&<Select label="Estado" value={v.estado} set={(x:string)=>setV({...v,estado:x})} options={['Programado','En_curso','Completado','Cancelado']}/>} {error&&<p className="sm:col-span-2 text-red-600">{error}</p>}<Button className="sm:col-span-2">{editing?'Guardar modificación':'Crear programación'}</Button></form></Dialog></>}
function Field({label,value,set,type='text',required=false}:any){return <label className="text-sm font-semibold">{label}<input type={type} value={value||''} onChange={e=>set(e.target.value)} required={required} className="mt-1.5 w-full rounded-xl border bg-transparent p-2.5 dark:border-slate-700"/></label>}
function Select({label,value,set,options,required=false}:any){useEffect(()=>{if(!value&&options[0])set(options[0])},[value,options[0]]);return <label className="text-sm font-semibold">{label}<select value={value||options[0]||''} onChange={e=>set(e.target.value)} required={required} className="mt-1.5 w-full rounded-xl border bg-white p-2.5 dark:border-slate-700 dark:bg-slate-900">{options.map((x:string)=><option key={x}>{x}</option>)}</select></label>}
