export type Field={name:string;label:string;type?:'text'|'email'|'date'|'datetime-local'|'time'|'number'|'textarea'|'select';required?:boolean;options?:string[]};
export type Module={key:string;title:string;singular:string;subtitle:string;fields:Field[];primary:string;secondary?:string;status?:string};
const estado=(options:string[]):Field=>({name:'estado',label:'Estado',type:'select',options});
export const modules:Record<string,Module>={
 guardias:{key:'guardia',title:'Guardias',singular:'guardia',subtitle:'Personal de seguridad y asignaciones',primary:'nombre',secondary:'documento',status:'estado',fields:[{name:'nombre',label:'Nombre completo',required:true},{name:'documento',label:'Documento',required:true},{name:'telefono',label:'Teléfono'},{name:'email',label:'Email',type:'email'},{name:'rango',label:'Rango',type:'select',options:['supervisor','guardia_senior','guardia','cabo','conserje','nochero']},estado(['Activo','Inactivo','Licencia','Suspendido']),{name:'fecha_ingreso',label:'Fecha de ingreso',type:'date'},{name:'foto_url',label:'URL de fotografía'},{name:'recinto_nombre',label:'Recinto asignado',type:'select',options:[]}]},
 recintos:{key:'recinto',title:'Recintos',singular:'recinto',subtitle:'Instalaciones y edificios vigilados',primary:'nombre',secondary:'direccion',status:'estado',fields:[{name:'nombre',label:'Nombre',required:true},{name:'direccion',label:'Dirección',required:true},{name:'tipo',label:'Tipo',type:'select',options:['Condominio','Departamento','Edificio','Complejo','Urbanización','Oficina','Otro']},{name:'encargado',label:'Encargado'},{name:'email',label:'Email',type:'email'},{name:'telefono',label:'Teléfono'},{name:'observaciones',label:'Observaciones',type:'textarea'},estado(['Activo','Inactivo'])]},
 turnos:{key:'turno',title:'Turnos',singular:'turno',subtitle:'Planificación y control de jornadas',primary:'guardia_nombre',secondary:'ubicacion',status:'estado',fields:[{name:'guardia_id',label:'ID guardia',required:true},{name:'guardia_nombre',label:'Guardia',required:true},{name:'tipo_turno',label:'Tipo',type:'select',options:['Manana','Tarde','Noche']},{name:'fecha',label:'Fecha',type:'date',required:true},{name:'hora_inicio',label:'Hora inicio',type:'time',required:true},{name:'hora_fin',label:'Hora fin',type:'time',required:true},{name:'ubicacion',label:'Ubicación'},{name:'observaciones',label:'Observaciones',type:'textarea'},estado(['Programado','En_curso','Completado','Cancelado']),{name:'recinto_id',label:'ID recinto'},{name:'recinto_nombre',label:'Recinto'}]},
 entradas:{key:'entrada',title:'Entradas',singular:'entrada',subtitle:'Registro de visitantes y vehículos',primary:'visitante_nombre',secondary:'motivo',status:'estado',fields:[{name:'visitante_nombre',label:'Visitante',required:true},{name:'visitante_documento',label:'Documento'},{name:'vehiculo',label:'Vehículo'},{name:'motivo',label:'Motivo'},{name:'persona_visita',label:'Persona visitada'},{name:'hora_entrada',label:'Hora entrada',type:'datetime-local',required:true},{name:'hora_salida',label:'Hora salida',type:'datetime-local'},{name:'guardia_id',label:'ID guardia'},{name:'guardia_nombre',label:'Guardia'},estado(['Dentro','Salio','Denegado']),{name:'recinto_id',label:'ID recinto'},{name:'recinto_nombre',label:'Recinto'}]},
 reportes:{key:'reporte',title:'Reportes',singular:'reporte',subtitle:'Novedades, incidencias y siniestros',primary:'titulo',secondary:'ubicacion',status:'estado',fields:[{name:'titulo',label:'Título',required:true},{name:'tipo',label:'Tipo',type:'select',options:['Novedad','Incidencia','Siniestro','Mantenimiento','Otro']},{name:'severidad',label:'Severidad',type:'select',options:['Baja','Media','Alta','Critica']},{name:'fecha',label:'Fecha y hora',type:'datetime-local',required:true},{name:'descripcion',label:'Descripción',type:'textarea'},{name:'ubicacion',label:'Ubicación'},{name:'guardia_nombre',label:'Guardia responsable',type:'select',options:[]},estado(['Abierto','En_revision','Resuelto','Cerrado']),{name:'recinto_nombre',label:'Recinto',type:'select',options:[]}]},
 alertas:{key:'alerta',title:'Alertas',singular:'alerta',subtitle:'Eventos críticos y seguimiento',primary:'titulo',secondary:'ubicacion',status:'estado',fields:[{name:'titulo',label:'Título',required:true},{name:'tipo',label:'Tipo',type:'select',options:['Intrusion','Emergencia','Sistema','Acceso_no_autorizado','Otro']},{name:'nivel',label:'Nivel',type:'select',options:['Info','Advertencia','Critica']},{name:'fecha',label:'Fecha y hora',type:'datetime-local',required:true},{name:'mensaje',label:'Mensaje',type:'textarea'},{name:'ubicacion',label:'Ubicación'},{name:'guardia_id',label:'ID guardia'},estado(['Activa','Atendida','Resuelta']),{name:'recinto_id',label:'ID recinto'},{name:'recinto_nombre',label:'Recinto'}]},
 rondas:{key:'ronda',title:'Rondas',singular:'ronda',subtitle:'Patrullas, trazado GPS y novedades',primary:'guardia_nombre',secondary:'puntos_recorridos',status:'estado',fields:[{name:'guardia_id',label:'ID guardia',required:true},{name:'guardia_nombre',label:'Guardia',required:true},{name:'fecha_hora_inicio',label:'Inicio',type:'datetime-local',required:true},{name:'fecha_hora_fin',label:'Fin',type:'datetime-local'},{name:'puntos_recorridos',label:'Puntos recorridos',type:'textarea'},{name:'novedades',label:'Novedades',type:'textarea'},estado(['Programada','En_curso','Completada','Incidente']),{name:'distancia_m',label:'Distancia (m)',type:'number'},{name:'recinto_id',label:'ID recinto'},{name:'recinto_nombre',label:'Recinto'}]}
};
