import { useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Globe, Mail, MapPin, Phone, Shield, UserRound } from 'lucide-react';
import { useBranding, type Branding } from '../branding';
import { api } from '../state';
import { Button } from '../components';

export default function PublicPage(){
  const{branding,loading}=useBranding();
  const[v,setV]=useState({nombre:'',email:'',telefono:'',empresa:'',mensaje:''});const[msg,setMsg]=useState('');const[error,setError]=useState('');
  if(loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-sm text-slate-300">Cargando…</main>;
  if(!branding.public_page_enabled)return <Navigate to="/login" replace/>;
  const submit=async(e:any)=>{e.preventDefault();setError('');try{const r=await api('/public/quote',{method:'POST',body:JSON.stringify(v)});setMsg(r.message);setV({nombre:'',email:'',telefono:'',empresa:'',mensaje:''})}catch(e){setError((e as Error).message)}};
  const services=(branding.company_services||'Guardias y supervisión\nRondas GPS en tiempo real\nControl de accesos y visitantes\nAlertas e informes operacionales').split('\n').filter(Boolean);
  const hex=(branding.public_banner_color||'#e2e8f0').replace('#','');const rgb=parseInt(hex,16);const luminance=((rgb>>16)*299+((rgb>>8)&255)*587+(rgb&255)*114)/1000;const bannerText=luminance>145?'#0f172a':'#ffffff';
  document.documentElement.style.setProperty('--public-banner-color',branding.public_banner_color||'#e2e8f0');document.documentElement.style.setProperty('--public-banner-text',bannerText);
  return <main className="min-h-screen bg-slate-950 text-white">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><div className="flex items-center gap-3">{branding.logo_url?<img src={branding.logo_url} alt={branding.brand_name} className="h-11 max-w-48 object-contain"/>:<span className="brand-bg grid size-11 place-items-center rounded-xl"><Shield/></span>}<div><b className="text-lg">{branding.brand_name}</b><p className="text-xs text-slate-400">{branding.brand_subtitle}</p></div></div><Link to="/login" className="rounded-xl border border-white/20 px-4 py-2 text-sm">Acceso empresa</Link></header>
    <section className="mx-auto grid max-w-6xl gap-12 px-5 py-16 lg:grid-cols-2 lg:items-center"><div><p className="brand-text mb-4 font-bold uppercase tracking-widest">BastControl profesional</p><h1 className="text-4xl font-bold leading-tight sm:text-6xl">{branding.company_title}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">{branding.company_description||branding.hero_description}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{services.map(s=><span key={s} className="flex items-center gap-2 text-slate-200"><CheckCircle2 className="brand-text" size={19}/>{s}</span>)}</div></div>{branding.hero_image_url&&<img src={branding.hero_image_url} alt="Imagen de la empresa" className="max-h-[480px] w-full rounded-3xl object-contain shadow-2xl"/>}</section>
    {branding.company_contact_enabled&&<Contact branding={branding}/>} 
    <section className="bg-white py-16 text-slate-900"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-2"><div><Mail className="brand-text" size={34}/><h2 className="mt-4 text-3xl font-bold">Solicita una cotización</h2><p className="mt-3 text-slate-500">Cuéntanos qué necesitas y nuestro equipo se pondrá en contacto contigo.</p></div><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{[['nombre','Nombre *'],['email','Email *'],['telefono','Teléfono'],['empresa','Empresa']].map(([n,l])=><input key={n} type={n==='email'?'email':'text'} required={n==='nombre'||n==='email'} placeholder={l} value={(v as any)[n]} onChange={e=>setV({...v,[n]:e.target.value})} className="rounded-xl border border-slate-200 p-3"/>)}<textarea required rows={4} placeholder="¿Qué servicio necesitas? *" value={v.mensaje} onChange={e=>setV({...v,mensaje:e.target.value})} className="rounded-xl border border-slate-200 p-3 sm:col-span-2"/>{error&&<p className="text-sm text-red-600 sm:col-span-2">{error}</p>}{msg&&<p className="text-sm text-emerald-600 sm:col-span-2">{msg}</p>}<Button className="sm:col-span-2">Enviar solicitud <ArrowRight size={17}/></Button></form></div></section>
  </main>;
}

function Contact({branding:b}:{branding:Branding}){const website=b.company_website_url&&(/^https?:\/\//i.test(b.company_website_url)?b.company_website_url:`https://${b.company_website_url}`);const rows=[{Icon:UserRound,value:b.company_contact_name},{Icon:Mail,value:b.company_email,href:b.company_email&&`mailto:${b.company_email}`},{Icon:Phone,value:b.company_phone,href:b.company_phone&&`tel:${b.company_phone}`},{Icon:MapPin,value:b.company_address},{Icon:Globe,value:b.company_website_url,href:website}];return <section className="bg-white/10 py-10"><div className="mx-auto max-w-6xl px-5"><h2 className="text-2xl font-bold">Datos de contacto</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.filter(x=>x.value).map(({Icon,value,href},i)=><div key={i} className="flex items-start gap-3 rounded-2xl border border-current/15 bg-white/10 p-4"><Icon className="mt-0.5 shrink-0" size={20}/><span className="break-words text-sm">{href?<a href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer" className="underline">{value}</a>:value}</span></div>)}</div></div></section>}
