import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,Archive,Download,FileHeart,FileUp,Mail,PauseCircle,Plus,Printer,RotateCcw,Search,Send,ShieldCheck,UserCheck,UserX,UsersRound } from 'lucide-react';
import { api,useAuth } from '../state';
import { Badge,Button,Dialog,EntityForm,PageHead } from '../components';
import type { Field } from '../config';

const workerFields:Field[]=[
  {name:'nombre',label:'Nombre completo',required:true},{name:'documento',label:'RUT / Documento',required:true},{name:'cargo',label:'Cargo',required:true},{name:'estado',label:'Estado laboral',type:'select',options:['Activo','Licencia','Vacaciones','Suspendido','Desvinculado']},
  {name:'fecha_nacimiento',label:'Fecha de nacimiento',type:'date'},{name:'nacionalidad',label:'Nacionalidad'},{name:'direccion',label:'Dirección'},{name:'comuna',label:'Comuna'},
  {name:'telefono',label:'Teléfono'},{name:'email_personal',label:'Correo personal',type:'email'},{name:'email_corporativo',label:'Correo corporativo',type:'email'},{name:'area',label:'Área'},
  {name:'supervisor',label:'Supervisor'},{name:'recinto',label:'Recinto / Lugar de trabajo'},{name:'fecha_ingreso',label:'Fecha de ingreso',type:'date'},{name:'tipo_contrato',label:'Tipo de contrato',type:'select',options:['Indefinido','Plazo_fijo','Obra_o_faena','Honorarios','Otro']},
  {name:'jornada',label:'Jornada'},{name:'contacto_emergencia_nombre',label:'Contacto de emergencia'},{name:'contacto_emergencia_parentesco',label:'Parentesco'},{name:'contacto_emergencia_telefono',label:'Teléfono de emergencia'},
  {name:'fecha_termino',label:'Fecha de término',type:'date'},{name:'motivo_termino',label:'Motivo de término'},{name:'observaciones',label:'Observaciones internas',type:'textarea'}
];
const eventTypes=['OS10','Curso','Credencial','Certificación','Licencia','Inasistencia','Atraso','Permiso','Vacaciones','Accidente','Capacitación','Contrato','Entrega de equipo','Evaluación','Otro'];
const warningFields:Field[]=[{name:'fecha_hecho',label:'Fecha y hora del hecho',type:'datetime-local',required:true},{name:'lugar',label:'Lugar'},{name:'tipo_incumplimiento',label:'Tipo de incumplimiento',required:true},{name:'responsable',label:'Responsable que emite',required:true},{name:'hechos',label:'Descripción objetiva de los hechos',type:'textarea',required:true},{name:'norma_relacionada',label:'Norma o cláusula relacionada',type:'textarea'},{name:'descargos',label:'Descargos del trabajador',type:'textarea'},{name:'medida',label:'Medida adoptada',type:'textarea'},{name:'testigos',label:'Testigos'},{name:'estado',label:'Estado',type:'select',options:['Borrador','Emitida','Notificada']}];

export default function RRHH(){
  const {user}=useAuth();const admin=user?.role==='admin';
  const [workers,setWorkers]=useState<any[]>([]),[summary,setSummary]=useState<any>({}),[selected,setSelected]=useState<any>(),[q,setQ]=useState(''),[showArchived,setShowArchived]=useState(false);
  const [dialog,setDialog]=useState<'worker'|'event'|'warning'|null>(null),[editing,setEditing]=useState<any>();const [notice,setNotice]=useState('');
  const load=async()=>{const [list,stats]=await Promise.all([api('/rrhh/trabajadores?archivados='+showArchived+'&q='+encodeURIComponent(q)),api('/rrhh/resumen')]);setWorkers(list);setSummary(stats);if(selected){const current=list.find((item:any)=>item.id===selected.id);if(current)await openWorker(current);else setSelected(undefined)}};
  useEffect(()=>{const timeout=setTimeout(load,200);return()=>clearTimeout(timeout)},[q,showArchived]);
  const openWorker=async(worker:any)=>setSelected(await api('/rrhh/trabajadores/'+worker.id));
  const saveWorker=async(value:any)=>{await api('/rrhh/trabajadores'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:JSON.stringify(value)});setDialog(null);setEditing(undefined);await load()};
  const saveEvent=async(value:any)=>{await api(`/rrhh/trabajadores/${selected.id}/eventos`,{method:'POST',body:JSON.stringify(value)});setDialog(null);await openWorker(selected);await load()};
  const saveWarning=async(value:any)=>{await api(`/rrhh/trabajadores/${selected.id}/amonestaciones`,{method:'POST',body:JSON.stringify(value)});setDialog(null);await openWorker(selected);await load()};
  const printWarning=async(item:any)=>{const {html}=await api(`/rrhh/amonestaciones/${item.id}/documento`);const popup=window.open('','_blank');if(!popup)return alert('El navegador bloqueó la ventana de impresión');popup.document.open();popup.document.write(html);popup.document.close()};
  const emailWarning=async(item:any)=>{const response=await api(`/rrhh/amonestaciones/${item.id}/enviar`,{method:'POST'});setNotice(response.message);await openWorker(selected)};
  const convertToGuard=async()=>{if(!confirm(`¿Convertir a ${selected.nombre} en guardia? Se conservará esta ficha de RR. HH.`))return;try{const response=await api(`/rrhh/trabajadores/${selected.id}/convertir-guardia`,{method:'POST',body:JSON.stringify({rango:'guardia'})});setNotice(response.message);await load();await openWorker(selected)}catch(error){setNotice((error as Error).message)}};
  const archiveWorker=async()=>{if(!confirm(`¿Archivar a ${selected.nombre}? Se conservarán su ficha, documentos e historial.`))return;try{const response=await api(`/rrhh/trabajadores/${selected.id}/archivar`,{method:'POST'});setNotice(response.message);setSelected(undefined);await load()}catch(error){setNotice((error as Error).message)}};
  const restoreWorker=async()=>{const response=await api(`/rrhh/trabajadores/${selected.id}/restaurar`,{method:'POST'});setNotice(response.message);setSelected(undefined);await load()};
  const exportExcel=async()=>{const token=localStorage.getItem('gp_token'),response=await fetch(`/api/rrhh/trabajadores-exportar?archivados=${showArchived}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok)throw new Error('No fue posible exportar trabajadores');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`trabajadores-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)};
  const events=useMemo(()=>selected?.eventos||[],[selected]);
  return <><PageHead title="Recursos Humanos" subtitle="Dotación, expedientes laborales, ausencias, permisos y documentación" action={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={exportExcel}><Download size={18}/>Exportar Excel</Button>{admin&&<Button onClick={()=>{setEditing(undefined);setDialog('worker')}}><Plus size={18}/>Nuevo trabajador</Button>}</div>}/>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[summary.activos,'Activos',UserCheck,'text-emerald-600'],[summary.inactivos,'Inactivos',UserX,'text-slate-500'],[summary.licencias,'Con licencia',FileHeart,'text-amber-600'],[summary.suspendidos,'Suspendidos',PauseCircle,'text-red-600']].map(([value,label,Icon,color]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><Icon className={color} size={21}/><b className="mt-3 block text-2xl">{value??'—'}</b><span className="text-xs text-slate-500">{label}</span></div>)}</div>
    <button onClick={()=>setShowArchived(!showArchived)} className="mb-4 inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold dark:border-slate-700 dark:bg-slate-900"><Archive size={16}/>{showArchived?'Volver a trabajadores':'Ver archivados'} ({summary.archivados||0})</button>
    <div className="grid gap-5 xl:grid-cols-[360px_1fr]">
      <section><div className="relative mb-3"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Buscar nombre, RUT o cargo…" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 dark:border-slate-700 dark:bg-slate-900"/></div><div className="space-y-2">{workers.map(worker=><button key={worker.id} onClick={()=>openWorker(worker)} className={`w-full rounded-xl border p-4 text-left ${selected?.id===worker.id?'border-teal-500 bg-teal-50 dark:bg-teal-950/40':'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`}><div className="flex justify-between gap-2"><b>{worker.nombre}</b><Badge tone={worker.estado==='Activo'?'green':worker.estado==='Desvinculado'?'red':'amber'}>{worker.estado}</Badge></div><p className="mt-1 text-sm text-slate-500">{worker.cargo} · {worker.documento}</p><p className="mt-2 text-xs text-slate-400">{worker._count?.eventos||0} registros · {worker._count?.amonestaciones||0} amonestaciones</p></button>)}</div></section>
      <section className="min-h-96 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">{selected?<><div className="flex flex-col justify-between gap-3 border-b border-slate-100 pb-5 dark:border-slate-800 sm:flex-row"><div><h2 className="text-xl font-bold">{selected.nombre}</h2><p className="text-sm text-slate-500">{selected.cargo} · {selected.area||'Sin área'} · {selected.recinto||'Sin recinto'}</p></div><div className="flex flex-wrap gap-2">{!showArchived&&admin&&<Button variant="secondary" onClick={()=>{setEditing(selected);setDialog('worker')}}>Editar ficha</Button>}{!showArchived&&admin&&!selected.guardia_id&&<Button variant="secondary" onClick={convertToGuard}><ShieldCheck size={16}/>Convertir en guardia</Button>}{!showArchived&&<Button variant="secondary" onClick={()=>setDialog('event')}><Plus size={16}/>Registro</Button>}{!showArchived&&admin&&<Button onClick={()=>setDialog('warning')}><AlertTriangle size={16}/>Amonestación</Button>}{admin&&(showArchived?<button onClick={restoreWorker} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm font-semibold text-teal-700 hover:bg-teal-50"><RotateCcw size={16}/>Restaurar</button>:<button onClick={archiveWorker} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm font-semibold text-amber-700 hover:bg-amber-50"><Archive size={16}/>Archivar</button>)}</div></div>
        <div className="grid gap-3 py-5 text-sm sm:grid-cols-2 lg:grid-cols-3"><Info label="Documento" value={selected.documento}/><Info label="Teléfono" value={selected.telefono}/><Info label="Correo" value={selected.email_corporativo||selected.email_personal}/><Info label="Dirección" value={[selected.direccion,selected.comuna].filter(Boolean).join(', ')}/><Info label="Contrato" value={selected.tipo_contrato}/><Info label="Ingreso" value={date(selected.fecha_ingreso)}/><Info label="Contacto de emergencia" value={selected.contacto_emergencia_nombre}/><Info label="Parentesco" value={selected.contacto_emergencia_parentesco}/><Info label="Teléfono emergencia" value={selected.contacto_emergencia_telefono}/></div>
        <h3 className="mb-3 font-bold">Expediente y línea de tiempo</h3><div className="space-y-2">{events.map((event:any)=><div key={event.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><div className="flex justify-between gap-3"><div><Badge>{event.tipo}</Badge><b className="ml-2 text-sm">{event.titulo}</b></div><span className="text-xs text-slate-500">{date(event.fecha_inicio)}{event.fecha_fin?` — ${date(event.fecha_fin)}`:''}</span></div>{event.detalle&&<p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{event.detalle}</p>}<div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-slate-500">{event.notificar_email&&<span className="inline-flex items-center gap-1"><Mail size={13}/>Aviso por correo</span>}{event.notificar_telegram&&<span className="inline-flex items-center gap-1"><Send size={13}/>Aviso por Telegram</span>}{event.archivo_url&&<a href={event.archivo_url} download={`${event.tipo}-${event.titulo}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-teal-700"><Download size={13}/>Ver o descargar archivo</a>}</div></div>)}{!events.length&&<p className="text-sm text-slate-500">El expediente todavía no tiene registros.</p>}</div>
        <h3 className="mb-3 mt-7 font-bold">Amonestaciones</h3><div className="space-y-2">{selected.amonestaciones?.map((item:any)=><div key={item.id} className="flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700 sm:flex-row sm:items-center"><div><b className="text-sm">{item.folio} · {item.tipo_incumplimiento}</b><p className="text-xs text-slate-500">{date(item.fecha_hecho)} · {item.estado}{item.enviada_email_at?' · Enviada por correo':''}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>printWarning(item)}><Printer size={15}/>Imprimir</Button>{admin&&<Button variant="secondary" onClick={()=>emailWarning(item)}><Mail size={15}/>Enviar</Button>}</div></div>)}{!selected.amonestaciones?.length&&<p className="text-sm text-slate-500">No existen amonestaciones registradas.</p>}</div>{notice&&<p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
      </>:<div className="grid min-h-80 place-items-center text-center text-slate-500"><div><UsersRound className="mx-auto mb-3" size={42}/><b>Selecciona un trabajador</b><p className="mt-1 text-sm">Verás su ficha y expediente laboral.</p></div></div>}</section>
    </div>
    <Dialog open={dialog==='worker'} onClose={()=>setDialog(null)} title={editing?'Editar trabajador':'Nuevo trabajador'}><EntityForm fields={workerFields} initial={editing} onSave={saveWorker} onCancel={()=>setDialog(null)}/></Dialog>
    <Dialog open={dialog==='event'} onClose={()=>setDialog(null)} title="Agregar al expediente"><EventForm onSave={saveEvent} onCancel={()=>setDialog(null)}/></Dialog>
    <Dialog open={dialog==='warning'} onClose={()=>setDialog(null)} title="Registrar amonestación"><EntityForm fields={warningFields} onSave={saveWarning} onCancel={()=>setDialog(null)}/></Dialog>
  </>;
}
const date=(value:any)=>value?new Date(value).toLocaleDateString('es-CL'):'Sin información';
function Info({label,value}:{label:string;value:any}){return <div><span className="block text-xs font-semibold uppercase text-slate-400">{label}</span><span>{value||'Sin información'}</span></div>}
function EventForm({onSave,onCancel}:{onSave:(value:any)=>Promise<void>;onCancel:()=>void}){
 const [v,setV]=useState<any>({tipo:'OS10',titulo:'',fecha_inicio:'',fecha_fin:'',estado:'Registrado',dias:'',entidad:'',folio:'',detalle:'',archivo_url:null,archivo_nombre:'',guardar_nextcloud:false,notificar_email:false,notificar_telegram:false}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const file=(selected?:File)=>{if(!selected)return;if(!['application/pdf','image/jpeg','image/png'].includes(selected.type))return setError('El archivo debe ser PDF, JPG o PNG');if(selected.size>8_000_000)return setError('El archivo no puede superar 8 MB');const cloud=confirm('¿Deseas guardar también una copia de este documento en Nextcloud?');const reader=new FileReader();reader.onload=()=>setV({...v,archivo_url:String(reader.result),archivo_nombre:selected.name,guardar_nextcloud:cloud});reader.readAsDataURL(selected)};
 const submit=async(e:any)=>{e.preventDefault();if(v.fecha_fin&&new Date(v.fecha_fin)<new Date(v.fecha_inicio))return setError('La fecha de término no puede ser anterior al inicio');setBusy(true);setError('');try{await onSave({...v,fecha_inicio:new Date(v.fecha_inicio).toISOString(),fecha_fin:v.fecha_fin?new Date(v.fecha_fin).toISOString():null})}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
 const fieldClass='mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700';
 return <form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Tipo de registro<select value={v.tipo} onChange={e=>setV({...v,tipo:e.target.value})} className={fieldClass+' bg-white dark:bg-slate-900'}>{eventTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Título *<input required value={v.titulo} onChange={e=>setV({...v,titulo:e.target.value})} className={fieldClass}/></label><label className="text-sm font-medium">Inicio *<input required type="datetime-local" value={v.fecha_inicio} onChange={e=>setV({...v,fecha_inicio:e.target.value})} className={fieldClass}/></label><label className="text-sm font-medium">Término<input type="datetime-local" value={v.fecha_fin} onChange={e=>setV({...v,fecha_fin:e.target.value})} className={fieldClass}/></label><label className="text-sm font-medium">Entidad relacionada<input value={v.entidad} onChange={e=>setV({...v,entidad:e.target.value})} className={fieldClass}/></label><label className="text-sm font-medium">Folio / Comprobante<input value={v.folio} onChange={e=>setV({...v,folio:e.target.value})} className={fieldClass}/></label><label className="sm:col-span-2 text-sm font-medium">Detalle<textarea rows={3} value={v.detalle} onChange={e=>setV({...v,detalle:e.target.value})} className={fieldClass}/></label><section className="sm:col-span-2 rounded-xl border border-dashed border-slate-300 p-4 dark:border-slate-700"><label className="flex cursor-pointer items-center gap-3"><FileUp className="text-teal-600"/><span><b className="block text-sm">Adjuntar documento</b><span className="text-xs text-slate-500">Disponible para todos los tipos · PDF, JPG o PNG · máximo 8 MB</span></span><input type="file" accept="application/pdf,image/jpeg,image/png" className="sr-only" onChange={e=>file(e.target.files?.[0])}/></label>{v.archivo_url&&<p className="mt-2 text-xs font-semibold text-emerald-700">Archivo preparado correctamente</p>}</section><section className="sm:col-span-2 rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><b className="text-sm">Notificar el inicio y el término</b><p className="mb-3 text-xs text-slate-500">Se enviará un aviso en ambas fechas por los canales seleccionados.</p><div className="flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={v.notificar_email} onChange={e=>setV({...v,notificar_email:e.target.checked})}/><Mail size={16}/>Correo</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={v.notificar_telegram} onChange={e=>setV({...v,notificar_telegram:e.target.checked})}/><Send size={16}/>Telegram</label></div></section></div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onCancel}>Cancelar</Button><Button disabled={busy}>{busy?'Guardando…':'Guardar registro'}</Button></div></form>
}
