import { useState } from 'react';
import { Camera, Trash2, UploadCloud } from 'lucide-react';
import type { Field } from '../config';
import { EntityForm } from '../components';

export default function GuardiaForm({fields,initial,onSave,onCancel}:{fields:Field[];initial?:any;onSave:(v:any)=>Promise<void>;onCancel:()=>void}){
  const[photo,setPhoto]=useState<string|null>(initial?.foto_url||null);
  const upload=(file?:File)=>{if(!file)return;if(file.size>2_000_000)return alert('La fotografía no puede superar 2 MB');if(!file.type.startsWith('image/'))return alert('Selecciona un archivo de imagen');const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result));reader.readAsDataURL(file)};
  return <><section className="mb-5 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="mb-3 flex items-center gap-2"><Camera size={18} className="text-teal-600"/><div><b className="text-sm">Fotografía del guardia</b><p className="text-xs text-slate-500">Recomendado: 600 × 600 px, máximo 2 MB.</p></div></div><label className="group grid min-h-44 cursor-pointer place-items-center overflow-hidden rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 hover:border-teal-500 dark:border-slate-700 dark:bg-slate-950">{photo?<img src={photo} alt="Fotografía del guardia" className="size-40 rounded-xl object-cover p-1"/>:<span className="flex flex-col items-center gap-2 text-slate-500 group-hover:text-teal-600"><UploadCloud size={32}/><b className="text-sm">Subir fotografía</b><span className="text-xs">PNG, JPG o WebP</span></span>}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label>{photo&&<button type="button" onClick={()=>setPhoto(null)} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-red-600"><Trash2 size={14}/>Quitar fotografía</button>}</section><EntityForm fields={fields.filter(f=>f.name!=='foto_url')} initial={initial} onSave={v=>onSave({...v,foto_url:photo})} onCancel={onCancel}/></>;
}
