import { Router } from 'express';
import { db,sendEmail } from './lib.js';
import { admin,asyncHandler,permit } from './middleware.js';

export const rrhh=Router();
rrhh.use(permit('rrhh'));
const dates=new Set(['fecha_nacimiento','fecha_ingreso','fecha_termino','fecha_inicio','fecha_fin','fecha_hecho','fecha_notificacion']);
const clean=(body:any,allowed:string[])=>Object.fromEntries(Object.entries(body).filter(([key])=>allowed.includes(key)).map(([key,value])=>[key,dates.has(key)&&value?new Date(String(value)):value===''?null:value]));
const workerFields=['nombre','documento','fecha_nacimiento','nacionalidad','direccion','comuna','telefono','email_personal','email_corporativo','contacto_emergencia_nombre','contacto_emergencia_parentesco','contacto_emergencia_telefono','cargo','area','supervisor','recinto','fecha_ingreso','tipo_contrato','jornada','estado','fecha_termino','motivo_termino','observaciones','foto_url','guardia_id','user_id'];
const eventFields=['tipo','titulo','fecha_inicio','fecha_fin','estado','dias','detalle','entidad','folio','archivo_url','confidencial'];
const warningFields=['fecha_hecho','lugar','tipo_incumplimiento','hechos','norma_relacionada','descargos','medida','responsable','testigos','fecha_notificacion','estado','constancia_recepcion'];
const audit=(req:any,accion:string,entidad:string,entidadId:string)=>console.info(`[AUDITORIA RRHH] ${new Date().toISOString()} usuario=${req.user?.id} accion=${accion} entidad=${entidad} id=${entidadId}`);

rrhh.get('/resumen',asyncHandler(async(_req,res)=>{const today=new Date();const month=new Date(today.getFullYear(),today.getMonth(),1);const [activos,licencias,ausencias,amonestaciones,contratos]=await Promise.all([db.trabajador.count({where:{estado:'Activo'}}),db.eventoRRHH.count({where:{tipo:'Licencia',fecha_inicio:{lte:today},OR:[{fecha_fin:null},{fecha_fin:{gte:today}}]}}),db.eventoRRHH.count({where:{tipo:'Inasistencia',fecha_inicio:{gte:month}}}),db.amonestacion.count({where:{fecha_hecho:{gte:month}}}),db.trabajador.count({where:{fecha_termino:{gte:today}}})]);res.json({activos,licencias,ausencias,amonestaciones,contratos});}));
rrhh.get('/trabajadores',asyncHandler(async(req,res)=>{const q=String(req.query.q||'');const data=await db.trabajador.findMany({where:q?{OR:[{nombre:{contains:q}},{documento:{contains:q}},{cargo:{contains:q}}]}:{},include:{_count:{select:{eventos:true,amonestaciones:true}}},orderBy:{nombre:'asc'}});res.json(data);}));
rrhh.post('/trabajadores',admin,asyncHandler(async(req,res)=>{const data:any=clean(req.body,workerFields);if(!data.nombre||!data.documento||!data.cargo)return res.status(400).json({message:'Nombre, documento y cargo son obligatorios'});const item=await db.trabajador.create({data:{...data,created_by_id:req.user!.id}});audit(req,'crear','trabajador',item.id);res.status(201).json(item);}));
rrhh.get('/trabajadores/:id',asyncHandler(async(req,res)=>{const item=await db.trabajador.findUniqueOrThrow({where:{id:req.params.id},include:{eventos:{orderBy:{fecha_inicio:'desc'}},amonestaciones:{orderBy:{fecha_hecho:'desc'}}}});audit(req,'ver','trabajador',item.id);res.json(item);}));
rrhh.put('/trabajadores/:id',admin,asyncHandler(async(req,res)=>{const item=await db.trabajador.update({where:{id:req.params.id},data:clean(req.body,workerFields)});audit(req,'editar','trabajador',item.id);res.json(item);}));

rrhh.post('/trabajadores/:id/eventos',asyncHandler(async(req,res)=>{const data:any=clean(req.body,eventFields);if(!data.tipo||!data.titulo||!data.fecha_inicio)return res.status(400).json({message:'Tipo, título y fecha son obligatorios'});const item=await db.eventoRRHH.create({data:{...data,trabajador_id:req.params.id,created_by_id:req.user!.id}});audit(req,'crear',data.tipo,item.id);res.status(201).json(item);}));
rrhh.put('/eventos/:id',asyncHandler(async(req,res)=>{const item=await db.eventoRRHH.update({where:{id:req.params.id},data:clean(req.body,eventFields)});audit(req,'editar','evento',item.id);res.json(item);}));

rrhh.post('/trabajadores/:id/amonestaciones',admin,asyncHandler(async(req,res)=>{const data:any=clean(req.body,warningFields);if(!data.fecha_hecho||!data.tipo_incumplimiento||!data.hechos||!data.responsable)return res.status(400).json({message:'Fecha, incumplimiento, hechos y responsable son obligatorios'});const folio=`AM-${new Date().getFullYear()}-${String((await db.amonestacion.count())+1).padStart(5,'0')}`;const item=await db.amonestacion.create({data:{...data,folio,trabajador_id:req.params.id,created_by_id:req.user!.id}});audit(req,'emitir','amonestacion',item.id);res.status(201).json(item);}));
rrhh.put('/amonestaciones/:id',admin,asyncHandler(async(req,res)=>{const existing=await db.amonestacion.findUniqueOrThrow({where:{id:req.params.id}});if(existing.estado!=='Borrador'&&req.body.estado!=='Anulada')return res.status(409).json({message:'Una amonestación emitida no puede modificarse; anúlala y crea una nueva versión'});const item=await db.amonestacion.update({where:{id:req.params.id},data:clean(req.body,warningFields)});audit(req,'editar','amonestacion',item.id);res.json(item);}));

async function warningHtml(id:string){const [item,config]=await Promise.all([db.amonestacion.findUniqueOrThrow({where:{id},include:{trabajador:true}}),db.configuracion.findUnique({where:{id:1}})]);const esc=(value:any)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(item.folio)}</title><style>@page{size:A4;margin:22mm}body{font:14px Arial;color:#172033;line-height:1.5}.head{display:flex;align-items:center;border-bottom:3px solid #0d9488;padding-bottom:16px;margin-bottom:25px}.logo{max-height:65px;max-width:180px}.brand{margin-left:18px}h1{font-size:21px;margin:0}.folio{margin-left:auto;text-align:right}.box{border:1px solid #cbd5e1;border-radius:8px;padding:14px;margin:14px 0}h2{font-size:14px;color:#0f766e;text-transform:uppercase}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:80px}.signature{border-top:1px solid #334155;text-align:center;padding-top:8px}.footer{margin-top:50px;font-size:11px;color:#64748b;text-align:center}@media print{button{display:none}}</style></head><body><button onclick="print()">Imprimir / Guardar PDF</button><div class="head">${config?.logo_url?`<img class="logo" src="${config.logo_url}">`:''}<div class="brand"><h1>${esc(config?.brand_name||'GuardiaPro')}</h1><div>${esc(config?.brand_subtitle||'Recursos Humanos')}</div></div><div class="folio"><b>${esc(item.folio)}</b><br>${new Date(item.fecha_hecho).toLocaleDateString('es-CL')}</div></div><h1>Carta de amonestación</h1><div class="box"><b>Trabajador:</b> ${esc(item.trabajador.nombre)}<br><b>Documento:</b> ${esc(item.trabajador.documento)}<br><b>Cargo:</b> ${esc(item.trabajador.cargo)}<br><b>Lugar:</b> ${esc(item.lugar||item.trabajador.recinto)}</div><h2>Incumplimiento</h2><p><b>${esc(item.tipo_incumplimiento)}</b></p><h2>Descripción objetiva de los hechos</h2><p>${esc(item.hechos)}</p>${item.norma_relacionada?`<h2>Norma relacionada</h2><p>${esc(item.norma_relacionada)}</p>`:''}${item.descargos?`<h2>Descargos del trabajador</h2><p>${esc(item.descargos)}</p>`:''}${item.medida?`<h2>Medida adoptada</h2><p>${esc(item.medida)}</p>`:''}<div class="signatures"><div class="signature">${esc(item.responsable)}<br>Representante del empleador</div><div class="signature">${esc(item.trabajador.nombre)}<br>Trabajador/a</div></div><div class="footer">Documento ${esc(item.folio)} · Generado por GuardiaPro RRHH · Conserve una copia en el expediente laboral.</div></body></html>`}
rrhh.get('/amonestaciones/:id/documento',asyncHandler(async(req,res)=>{audit(req,'imprimir','amonestacion',req.params.id);res.json({html:await warningHtml(req.params.id)})}));
rrhh.post('/amonestaciones/:id/enviar',admin,asyncHandler(async(req,res)=>{const item=await db.amonestacion.findUniqueOrThrow({where:{id:req.params.id},include:{trabajador:true}});const email=item.trabajador.email_corporativo||item.trabajador.email_personal;if(!email)return res.status(400).json({message:'El trabajador no tiene correo registrado'});await sendEmail(email,`Carta de amonestación ${item.folio}`,`Se adjunta para notificación el documento ${item.folio}.\n\nIncumplimiento: ${item.tipo_incumplimiento}\nFecha del hecho: ${item.fecha_hecho.toLocaleDateString('es-CL')}\n\nIngresa a la plataforma o solicita una copia impresa a Recursos Humanos.`);await db.amonestacion.update({where:{id:item.id},data:{enviada_email_at:new Date(),estado:item.estado==='Borrador'?'Notificada':item.estado}});audit(req,'enviar_correo','amonestacion',item.id);res.json({message:`Amonestación enviada a ${email}`});}));
