import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,CalendarOff,FileHeart,Mail,Plus,Printer,Search,UsersRound } from 'lucide-react';
import { api,useAuth } from '../state';
import { Badge,Button,Dialog,EntityForm,PageHead } from '../components';
import type { Field } from '../config';

const workerFields:Field[]=[
  {name:'nombre',label:'Nombre completo',required:true},{name:'documento',label:'RUT / Documento',required:true},{name:'cargo',label:'Cargo',required:true},{name:'estado',label:'Estado laboral',type:'select',options:['Activo','Licencia','Vacaciones','Suspendido','Desvinculado']},
  {name:'fecha_nacimiento',label:'Fecha de nacimiento',type:'date'},{name:'nacionalidad',label:'Nacionalidad'},{name:'direccion',label:'Dirección'},{name:'comuna',label:'Comuna'},
  {name:'telefono',label:'Teléfono'},{name:'email_personal',label:'Correo personal',type:'email'},{name:'email_corporativo',label:'Correo corporativo',type:'email'},{name:'area',label:'Área'},
  {name:'supervisor',label:'Supervisor'},{name:'recinto',label:'Recinto / Lugar de trabajo'},{name:'fecha_ingreso',label:'Fecha de ingreso',type:'date'},{name:'tipo_contrato',label:'Tipo de contrato',type:'select',options:['Indefinido','Plazo_fijo','Obra_o_faena','Honorarios','Otro']},
  {name:'jornada',label:'Jornada'},{name:'contacto_emergencia_nombre',label:'Contacto de emergencia'},{name:'contacto_emergencia_parentesco',label:'Parentesco'},{name:'contacto_emergencia_telefono',label:'Teléfono de emergencia'},
  {name:'fecha_termino',label:'Fecha de término',type:'date'},{name:'motivo_termino',label:'Motivo de término'},{name:'observaciones',label:'Observaciones internas',type:'textarea'}
];
const eventFields:Field[]=[{name:'tipo',label:'Tipo de registro',type:'select',options:['Licencia','Inasistencia','Atraso','Permiso','Vacaciones','Accidente','Capacitacion','Certificacion','Contrato','Entrega_equipo','Evaluacion','Otro']},{name:'titulo',label:'Título',required:true},{name:'fecha_inicio',label:'Inicio',type:'datetime-local',required:true},{name:'fecha_fin',label:'Término',type:'datetime-local'},{name:'estado',label:'Estado',type:'select',options:['Registrado','Pendiente','Aprobado','Rechazado','Cerrado']},{name:'dias',label:'Días / Cantidad',type:'number'},{name:'entidad',label:'Entidad relacionada'},{name:'folio',label:'Folio / Comprobante'},{name:'detalle',label:'Detalle',type:'textarea'}];
const warningFields:Field[]=[{name:'fecha_hecho',label:'Fecha y hora del hecho',type:'datetime-local',required:true},{name:'lugar',label:'Lugar'},{name:'tipo_incumplimiento',label:'Tipo de incumplimiento',required:true},{name:'responsable',label:'Responsable que emite',required:true},{name:'hechos',label:'Descripción objetiva de los hechos',type:'textarea',required:true},{name:'norma_relacionada',label:'Norma o cláusula relacionada',type:'textarea'},{name:'descargos',label:'Descargos del trabajador',type:'textarea'},{name:'medida',label:'Medida adoptada',type:'textarea'},{name:'testigos',label:'Testigos'},{name:'estado',label:'Estado',type:'select',options:['Borrador','Emitida','Notificada']}];

export default function RRHH(){
  const {user}=useAuth();const admin=user?.role==='admin';
  const [workers,setWorkers]=useState<any[]>([]),[summary,setSummary]=useState<any>({}),[selected,setSelected]=useState<any>(),[q,setQ]=useState('');
  const [dialog,setDialog]=useState<'worker'|'event'|'warning'|null>(null),[editing,setEditing]=useState<any>();const [notice,setNotice]=useState('');
  const load=async()=>{const [list,stats]=await Promise.all([api('/rrhh/trabajadores?q='+encodeURIComponent(q)),api('/rrhh/resumen')]);setWorkers(list);setSummary(stats);if(selected){const current=list.find((item:any)=>item.id===selected.id);if(current)await openWorker(current)}};
  useEffect(()=>{const timeout=setTimeout(load,200);return()=>clearTimeout(timeout)},[q]);
  const openWorker=async(worker:any)=>setSelected(await api('/rrhh/trabajadores/'+worker.id));
  const saveWorker=async(value:any)=>{await api('/rrhh/trabajadores'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:JSON.stringify(value)});setDialog(null);setEditing(undefined);await load()};
  const saveEvent=async(value:any)=>{await api(`/rrhh/trabajadores/${selected.id}/eventos`,{method:'POST',body:JSON.stringify(value)});setDialog(null);await openWorker(selected);await load()};
  const saveWarning=async(value:any)=>{await api(`/rrhh/trabajadores/${selected.id}/amonestaciones`,{method:'POST',body:JSON.stringify(value)});setDialog(null);await openWorker(selected);await load()};
  const printWarning=async(item:any)=>{const {html}=await api(`/rrhh/amonestaciones/${item.id}/documento`);const popup=window.open('','_blank');if(!popup)return alert('El navegador bloqueó la ventana de impresión');popup.document.open();popup.document.write(html);popup.document.close()};
  const emailWarning=async(item:any)=>{const response=await api(`/rrhh/amonestaciones/${item.id}/enviar`,{method:'POST'});setNotice(response.message);await openWorker(selected)};
  const events=useMemo(()=>selected?.eventos||[],[selected]);
  return <><PageHead title="Recursos Humanos" subtitle="Dotación, expedientes laborales, ausencias, permisos y documentación" action={admin?<Button onClick={()=>{setEditing(undefined);setDialog('worker')}}><Plus size={18}/>Nuevo trabajador</Button>:undefined}/>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{[[summary.activos,'Trabajadores activos',UsersRound,'text-teal-600'],[summary.licencias,'Licencias vigentes',FileHeart,'text-blue-600'],[summary.ausencias,'Inasistencias del mes',CalendarOff,'text-amber-600'],[summary.amonestaciones,'Amonestaciones del mes',AlertTriangle,'text-red-600'],[summary.contratos,'Contratos con término',FileHeart,'text-violet-600']].map(([value,label,Icon,color]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><Icon className={color} size={21}/><b className="mt-3 block text-2xl">{value??'—'}</b><span className="text-xs text-slate-500">{label}</span></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[360px_1fr]">
      <section><div className="relative mb-3"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Buscar nombre, RUT o cargo…" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 dark:border-slate-700 dark:bg-slate-900"/></div><div className="space-y-2">{workers.map(worker=><button key={worker.id} onClick={()=>openWorker(worker)} className={`w-full rounded-xl border p-4 text-left ${selected?.id===worker.id?'border-teal-500 bg-teal-50 dark:bg-teal-950/40':'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`}><div className="flex justify-between gap-2"><b>{worker.nombre}</b><Badge tone={worker.estado==='Activo'?'green':worker.estado==='Desvinculado'?'red':'amber'}>{worker.estado}</Badge></div><p className="mt-1 text-sm text-slate-500">{worker.cargo} · {worker.documento}</p><p className="mt-2 text-xs text-slate-400">{worker._count?.eventos||0} registros · {worker._count?.amonestaciones||0} amonestaciones</p></button>)}</div></section>
      <section className="min-h-96 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">{selected?<><div className="flex flex-col justify-between gap-3 border-b border-slate-100 pb-5 dark:border-slate-800 sm:flex-row"><div><h2 className="text-xl font-bold">{selected.nombre}</h2><p className="text-sm text-slate-500">{selected.cargo} · {selected.area||'Sin área'} · {selected.recinto||'Sin recinto'}</p></div><div className="flex flex-wrap gap-2">{admin&&<Button variant="secondary" onClick={()=>{setEditing(selected);setDialog('worker')}}>Editar ficha</Button>}<Button variant="secondary" onClick={()=>setDialog('event')}><Plus size={16}/>Registro</Button>{admin&&<Button onClick={()=>setDialog('warning')}><AlertTriangle size={16}/>Amonestación</Button>}</div></div>
        <div className="grid gap-3 py-5 text-sm sm:grid-cols-2 lg:grid-cols-3"><Info label="Documento" value={selected.documento}/><Info label="Teléfono" value={selected.telefono}/><Info label="Correo" value={selected.email_corporativo||selected.email_personal}/><Info label="Dirección" value={[selected.direccion,selected.comuna].filter(Boolean).join(', ')}/><Info label="Contrato" value={selected.tipo_contrato}/><Info label="Ingreso" value={date(selected.fecha_ingreso)}/><Info label="Contacto de emergencia" value={selected.contacto_emergencia_nombre}/><Info label="Parentesco" value={selected.contacto_emergencia_parentesco}/><Info label="Teléfono emergencia" value={selected.contacto_emergencia_telefono}/></div>
        <h3 className="mb-3 font-bold">Expediente y línea de tiempo</h3><div className="space-y-2">{events.map((event:any)=><div key={event.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><div className="flex justify-between gap-3"><div><Badge>{event.tipo}</Badge><b className="ml-2 text-sm">{event.titulo}</b></div><span className="text-xs text-slate-500">{date(event.fecha_inicio)}</span></div>{event.detalle&&<p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{event.detalle}</p>}</div>)}{!events.length&&<p className="text-sm text-slate-500">El expediente todavía no tiene registros.</p>}</div>
        <h3 className="mb-3 mt-7 font-bold">Amonestaciones</h3><div className="space-y-2">{selected.amonestaciones?.map((item:any)=><div key={item.id} className="flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700 sm:flex-row sm:items-center"><div><b className="text-sm">{item.folio} · {item.tipo_incumplimiento}</b><p className="text-xs text-slate-500">{date(item.fecha_hecho)} · {item.estado}{item.enviada_email_at?' · Enviada por correo':''}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>printWarning(item)}><Printer size={15}/>Imprimir</Button>{admin&&<Button variant="secondary" onClick={()=>emailWarning(item)}><Mail size={15}/>Enviar</Button>}</div></div>)}{!selected.amonestaciones?.length&&<p className="text-sm text-slate-500">No existen amonestaciones registradas.</p>}</div>{notice&&<p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
      </>:<div className="grid min-h-80 place-items-center text-center text-slate-500"><div><UsersRound className="mx-auto mb-3" size={42}/><b>Selecciona un trabajador</b><p className="mt-1 text-sm">Verás su ficha y expediente laboral.</p></div></div>}</section>
    </div>
    <Dialog open={dialog==='worker'} onClose={()=>setDialog(null)} title={editing?'Editar trabajador':'Nuevo trabajador'}><EntityForm fields={workerFields} initial={editing} onSave={saveWorker} onCancel={()=>setDialog(null)}/></Dialog>
    <Dialog open={dialog==='event'} onClose={()=>setDialog(null)} title="Agregar al expediente"><EntityForm fields={eventFields} onSave={saveEvent} onCancel={()=>setDialog(null)}/></Dialog>
    <Dialog open={dialog==='warning'} onClose={()=>setDialog(null)} title="Registrar amonestación"><EntityForm fields={warningFields} onSave={saveWarning} onCancel={()=>setDialog(null)}/></Dialog>
  </>;
}
const date=(value:any)=>value?new Date(value).toLocaleDateString('es-CL'):'Sin información';
function Info({label,value}:{label:string;value:any}){return <div><span className="block text-xs font-semibold uppercase text-slate-400">{label}</span><span>{value||'Sin información'}</span></div>}
