import { Image, Palette, Trash2, UploadCloud } from 'lucide-react';
import { api } from '../state';

const themes=[['esmeralda','Esmeralda','#0d9488'],['oceano','Océano','#2563eb'],['borgona','Borgoña','#be123c'],['arena','Arena','#b45309'],['grafito','Grafito','#374151']];
const field='mt-1.5 w-full rounded-xl border border-slate-200 bg-transparent p-2.5 dark:border-slate-700';

export default function BrandingSettings({v,setV}:{v:any;setV:(x:any)=>void}){
  const change=(name:string,value:any)=>setV({...v,[name]:value});
  const upload=(name:string,file?:File)=>{if(!file)return;if(file.size>2_000_000)return alert('La imagen no puede superar 2 MB');const reader=new FileReader();reader.onload=()=>change(name,reader.result);reader.readAsDataURL(file)};
  return <>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <div className="mb-5 flex items-center gap-2"><Palette className="text-teal-600"/><div><h2 className="text-lg font-bold">Tema e identidad visual</h2><p className="text-sm text-slate-500">Personaliza los colores y la marca visible en toda la plataforma.</p></div></div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{themes.map(([id,label,color])=><button type="button" key={id} onClick={()=>change('theme',id)} className={`rounded-xl border-2 p-3 text-left ${v.theme===id?'border-slate-900 dark:border-white':'border-transparent bg-slate-50 dark:bg-slate-950'}`}><span className="mb-2 block h-8 rounded-lg" style={{backgroundColor:color}}/><b className="text-sm">{label}</b></button>)}</div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><Text label="Nombre de marca" name="brand_name" v={v} change={change}/><Text label="Subtítulo" name="brand_subtitle" v={v} change={change}/><Text label="Título principal" name="hero_title" v={v} change={change}/><Text label="Frase final" name="hero_footer" v={v} change={change}/><label className="text-sm font-semibold sm:col-span-2">Descripción principal<textarea rows={3} value={v.hero_description||''} onChange={e=>change('hero_description',e.target.value)} className={field}/></label></div>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <div className="mb-5 flex items-center gap-2"><Image className="text-purple-600"/><div><h2 className="text-lg font-bold">Imágenes corporativas</h2><p className="text-sm text-slate-500">PNG, JPG, WebP o SVG; máximo 2 MB por imagen. La vista conserva la proporción y no deforma el archivo.</p></div></div>
      <div className="grid items-start gap-4 lg:grid-cols-3">
        <Upload label="Logo" help="Recomendado: 800 × 300 px" ratio="aspect-[8/3]" value={v.logo_url} onFile={(f:File)=>upload('logo_url',f)} clear={()=>change('logo_url',null)}/>
        <Upload label="Icono de barra lateral y sitio" help="Se muestra junto al nombre de marca. Recomendado: 512 × 512 px" ratio="aspect-square" value={v.icon_url} onFile={(f:File)=>upload('icon_url',f)} clear={()=>change('icon_url',null)}/>
        <Upload label="Imagen principal" help="Recomendado: 1600 × 900 px" ratio="aspect-video" value={v.hero_image_url} onFile={(f:File)=>upload('hero_image_url',f)} clear={()=>change('hero_image_url',null)}/>
      </div>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <h2 className="text-lg font-bold">Bloqueo de acceso</h2><p className="mt-1 text-sm text-slate-500">Configura el bloqueo temporal cuando se ingresan contraseñas incorrectas.</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><Text label="Intentos fallidos permitidos" name="login_max_attempts" type="number" v={v} change={change}/><Text label="Duración del bloqueo (minutos)" name="login_lock_minutes" type="number" v={v} change={change}/></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold dark:bg-slate-950"><input type="checkbox" checked={!!v.login_ban_email_enabled} onChange={e=>change('login_ban_email_enabled',e.target.checked)}/>Notificar bloqueo por correo</label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold dark:bg-slate-950"><input type="checkbox" checked={!!v.login_ban_telegram_enabled} onChange={e=>change('login_ban_telegram_enabled',e.target.checked)}/>Notificar bloqueo por Telegram</label></div>
      <p className="mt-3 text-xs text-slate-500">El correo se envía al destinatario configurado en Avisos. Telegram requiere el bot activado.</p>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <h2 className="text-lg font-bold">Documentos en Nextcloud</h2><p className="mt-1 text-sm text-slate-500">Conecta una cuenta mediante WebDAV para respaldar documentos de Recursos Humanos.</p>
      <label className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold dark:bg-slate-950"><input type="checkbox" checked={!!v.nextcloud_enabled} onChange={e=>change('nextcloud_enabled',e.target.checked)}/>Activar integración Nextcloud</label>
      {v.nextcloud_enabled&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><Text label="URL de Nextcloud" name="nextcloud_url" type="url" v={v} change={change}/><Text label="Usuario" name="nextcloud_user" v={v} change={change}/><Text label="Contraseña de aplicación" name="nextcloud_password" type="password" v={v} change={change}/><Text label="Carpeta base" name="nextcloud_folder" v={v} change={change}/></div>}
      <p className="mt-3 text-xs text-slate-500">Ejemplo de URL: https://cloud.empresa.cl. Usa una contraseña de aplicación, no la contraseña principal.</p>
      {v.nextcloud_enabled&&<button type="button" onClick={async()=>{try{alert((await api('/config/test-nextcloud',{method:'POST',body:'{}'})).message)}catch(error){alert((error as Error).message)}}} className="mt-4 rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold dark:border-slate-700">Probar conexión guardada</button>}
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
      <h2 className="text-lg font-bold">Turnos, fecha y hora</h2><p className="mt-1 text-sm text-slate-500">Define horarios y colores para distinguir claramente cada jornada.</p>
      <label className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><input type="checkbox" checked={!!v.shift_email_enabled} onChange={e=>change('shift_email_enabled',e.target.checked)}/><span><b>Enviar programación por correo al guardia</b><small className="block text-slate-500">Requiere email del guardia y SMTP configurado.</small></span></label>
      <div className="mt-5 grid gap-4 sm:grid-cols-3"><Text label="Zona horaria" name="timezone" v={v} change={change}/><Text label="Formato de fecha" name="date_format" v={v} change={change}/><Text label="Formato de hora" name="time_format" v={v} change={change}/></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><ShiftStyle title="Turno de día" colorName="turno_dia_color" startName="turno_dia_inicio" endName="turno_dia_fin" v={v} change={change}/><ShiftHours title="Turno de mañana" startName="turno_manana_inicio" endName="turno_manana_fin" v={v} change={change}/><ShiftHours title="Turno de tarde" startName="turno_tarde_inicio" endName="turno_tarde_fin" v={v} change={change}/><ShiftStyle title="Turno de noche" colorName="turno_noche_color" startName="turno_noche_inicio" endName="turno_noche_fin" v={v} change={change}/><div className="rounded-xl border p-4 dark:border-slate-700"><h3 className="mb-3 font-bold">Turno personalizado</h3><Color label="Color" name="turno_personalizado_color" v={v} change={change}/><p className="mt-3 text-xs text-slate-500">El horario se define al crear cada turno.</p></div></div>
    </section>
  </>;
}

function Text({label,name,v,change,type='text'}:any){const choices:Record<string,[string,string][]>= {timezone:[['America/Santiago','Santiago de Chile'],['America/Buenos_Aires','Buenos Aires'],['America/Lima','Lima'],['America/Bogota','Bogotá'],['America/Mexico_City','Ciudad de México'],['America/New_York','Nueva York'],['Europe/Madrid','Madrid'],['UTC','UTC']],date_format:[['DD/MM/YYYY','DD/MM/YYYY'],['MM/DD/YYYY','MM/DD/YYYY'],['YYYY-MM-DD','YYYY-MM-DD']],time_format:[['24h','24 horas'],['12h','12 horas (a. m./p. m.)']]};return <label className="text-sm font-semibold">{label}{choices[name]?<select value={v[name]||choices[name][0][0]} onChange={e=>change(name,e.target.value)} className={field}>{choices[name].map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>:<input type={type} value={v[name]||''} onChange={e=>change(name,e.target.value)} className={field}/>}</label>}
function Color({label,name,v,change}:any){return <label className="text-sm font-semibold">{label}<div className="mt-1.5 flex items-center gap-2"><input type="color" value={v[name]||'#64748b'} onChange={e=>change(name,e.target.value)} className="h-10 w-14 cursor-pointer rounded border p-1"/><input value={v[name]||''} onChange={e=>change(name,e.target.value)} pattern="#[0-9a-fA-F]{6}" className={field+' mt-0'}/></div></label>}
function ShiftStyle({title,colorName,startName,endName,v,change}:any){return <div className="rounded-xl border p-4 dark:border-slate-700"><h3 className="mb-3 font-bold">{title}</h3><div className="space-y-3"><Color label="Color" name={colorName} v={v} change={change}/><Text label="Hora de inicio" name={startName} type="time" v={v} change={change}/><Text label="Hora de término" name={endName} type="time" v={v} change={change}/></div></div>}
function ShiftHours({title,startName,endName,v,change}:any){return <div className="rounded-xl border p-4 dark:border-slate-700"><h3 className="mb-3 font-bold">{title}</h3><div className="space-y-3"><Text label="Hora de inicio" name={startName} type="time" v={v} change={change}/><Text label="Hora de término" name={endName} type="time" v={v} change={change}/></div></div>}

function Upload({label,help,ratio,value,onFile,clear}:any){return <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div><b className="text-sm">{label}</b><p className="mt-0.5 text-xs text-slate-500">{help}</p></div><label className={`group my-3 grid w-full cursor-pointer place-items-center overflow-hidden rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 transition hover:border-purple-500 hover:bg-purple-50 dark:border-slate-700 dark:bg-slate-950 dark:hover:border-purple-500 ${ratio}`}>{value?<img src={value} alt={`Vista previa de ${label}`} className="h-full w-full object-contain p-2"/>:<span className="flex flex-col items-center gap-2 px-4 text-center text-slate-500 group-hover:text-purple-600"><UploadCloud size={32}/><span className="text-sm font-semibold">Subir imagen</span><span className="text-xs">Haz clic para seleccionar</span></span>}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>onFile(e.target.files?.[0])} className="sr-only"/></label>{value&&<button type="button" onClick={clear} className="inline-flex items-center gap-1.5 text-xs font-semibold text-red-600 hover:text-red-700"><Trash2 size={14}/>Quitar imagen</button>}</div>}
