USE guardiapro;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE AFTER email_verified;
ALTER TABLE configuracion
  ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(190) NULL,
  ADD COLUMN IF NOT EXISTS smtp_port SMALLINT UNSIGNED NOT NULL DEFAULT 587,
  ADD COLUMN IF NOT EXISTS smtp_secure BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(190) NULL,
  ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS mail_from VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS telegram_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS telegram_bot_token VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS telegram_chat_id VARCHAR(100) NULL;
