import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { db } from './lib.js';
import { admin, asyncHandler, auth } from './middleware.js';

export const databaseAdmin = Router();
const backupSchema=z.object({format:z.literal('guardiapro-backup'),version:z.literal(1),data:z.object({recintos:z.array(z.record(z.any())),guardias:z.array(z.record(z.any())),turnos:z.array(z.record(z.any())),rondas:z.array(z.record(z.any())),entradas:z.array(z.record(z.any())),reportes:z.array(z.record(z.any())),alertas:z.array(z.record(z.any())),relevos:z.array(z.record(z.any())).optional().default([]),configuracion:z.record(z.any()).nullable().optional()})});
const configurationFields=['permitir_registro_publico','smtp_host','smtp_port','smtp_secure','smtp_user','mail_from','telegram_enabled','telegram_chat_id','theme','brand_name','brand_subtitle','hero_title','hero_description','hero_footer','logo_url','icon_url','hero_image_url','public_page_enabled','public_banner_color','company_contact_enabled','company_contact_name','company_email','company_phone','company_address','company_website_url','company_title','company_description','company_services','quote_email'] as const;
const dateFields:Record<string,string[]>={recintos:['created_at','updated_at'],guardias:['fecha_ingreso','created_at','updated_at'],turnos:['fecha','created_at','updated_at'],rondas:['fecha_hora_inicio','fecha_hora_fin','created_at','updated_at'],entradas:['hora_entrada','hora_salida','created_at','updated_at'],reportes:['fecha','created_at','updated_at'],alertas:['fecha','created_at','updated_at'],relevos:['fecha_hora','created_at','updated_at']};
function rowsForImport(name:string,rows:Record<string,any>[],userIds:Set<string>){return rows.map(row=>{const value={...row};for(const field of dateFields[name]||[])if(value[field])value[field]=new Date(value[field]);if('created_by_id'in value&&!userIds.has(value.created_by_id))value.created_by_id=null;return value})}
async function clearOperationalData(tx:any){await tx.relevo.deleteMany();await tx.alerta.deleteMany();await tx.reporte.deleteMany();await tx.entrada.deleteMany();await tx.ronda.deleteMany();await tx.turno.deleteMany();await tx.guardia.deleteMany();await tx.recinto.deleteMany()}

databaseAdmin.get('/export',auth,admin,asyncHandler(async(_req,res)=>{const[recintos,guardias,turnos,rondas,entradas,reportes,alertas,relevos,config]=await Promise.all([db.recinto.findMany(),db.guardia.findMany(),db.turno.findMany(),db.ronda.findMany(),db.entrada.findMany(),db.reporte.findMany(),db.alerta.findMany(),db.relevo.findMany(),db.configuracion.findUnique({where:{id:1}})]);const configuracion=config?Object.fromEntries(configurationFields.map(key=>[key,config[key]])):null;res.setHeader('Content-Disposition',`attachment; filename="guardiapro-${new Date().toISOString().slice(0,10)}.json"`);res.json({format:'guardiapro-backup',version:1,exported_at:new Date().toISOString(),data:{recintos,guardias,turnos,rondas,entradas,reportes,alertas,relevos,configuracion}})}));
databaseAdmin.post('/clear',auth,admin,asyncHandler(async(req,res)=>{const{password}=z.object({password:z.string().min(1)}).parse(req.body);const user=await db.user.findUnique({where:{id:req.user!.id}});if(!user?.password||!await bcrypt.compare(password,user.password))return res.status(401).json({message:'Contraseña incorrecta'});await db.$transaction(clearOperationalData);res.json({message:'Base de datos operativa limpiada. Los usuarios y la configuración se conservaron.'})}));
databaseAdmin.post('/import',auth,admin,asyncHandler(async(req,res)=>{const backup=backupSchema.parse(req.body);const userIds=new Set((await db.user.findMany({select:{id:true}})).map(user=>user.id));await db.$transaction(async tx=>{await clearOperationalData(tx);const d=backup.data;if(d.recintos.length)await tx.recinto.createMany({data:rowsForImport('recintos',d.recintos,userIds) as any});if(d.guardias.length)await tx.guardia.createMany({data:rowsForImport('guardias',d.guardias,userIds) as any});if(d.turnos.length)await tx.turno.createMany({data:rowsForImport('turnos',d.turnos,userIds) as any});if(d.rondas.length)await tx.ronda.createMany({data:rowsForImport('rondas',d.rondas,userIds) as any});if(d.entradas.length)await tx.entrada.createMany({data:rowsForImport('entradas',d.entradas,userIds) as any});if(d.reportes.length)await tx.reporte.createMany({data:rowsForImport('reportes',d.reportes,userIds) as any});if(d.alertas.length)await tx.alerta.createMany({data:rowsForImport('alertas',d.alertas,userIds) as any});if(d.relevos.length)await tx.relevo.createMany({data:rowsForImport('relevos',d.relevos,userIds) as any});if(d.configuracion){const config=Object.fromEntries(Object.entries(d.configuracion).filter(([key])=>(configurationFields as readonly string[]).includes(key)));await tx.configuracion.upsert({where:{id:1},update:config,create:{id:1,...config}})}});res.json({message:'Base de datos importada correctamente. Los usuarios existentes se conservaron.'})}));
