import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { audit,db,publicUser } from './lib.js';
import { asyncHandler,superadmin } from './middleware.js';

export const empresas=Router();
empresas.use(superadmin);
const modules=['guardias','turnos','relevos','rondas','recintos','entradas','reportes','alertas','rrhh','usuarios','configuracion'] as const;
const schema=z.object({nombre:z.string().min(2),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),rut:z.string().optional().nullable(),email:z.string().email().optional().nullable(),telefono:z.string().optional().nullable(),direccion:z.string().optional().nullable(),logo_url:z.string().optional().nullable(),estado:z.enum(['Activa','Suspendida','Eliminada']).default('Activa'),modulos:z.record(z.boolean()).default(Object.fromEntries(modules.map(x=>[x,true]))),limite_usuarios:z.number().int().positive().optional().nullable(),limite_guardias:z.number().int().positive().optional().nullable(),limite_recintos:z.number().int().positive().optional().nullable(),vence_at:z.coerce.date().optional().nullable()});
empresas.get('/',asyncHandler(async(_req,res)=>res.json(await db.empresa.findMany({where:{estado:{not:'Eliminada'}},include:{_count:{select:{users:true,guardias:true,recintos:true}}},orderBy:{nombre:'asc'}}))));
empresas.get('/:id',asyncHandler(async(req,res)=>res.json(await db.empresa.findUniqueOrThrow({where:{id:req.params.id},include:{users:{select:{id:true,full_name:true,email:true,role:true,enabled:true}},_count:{select:{guardias:true,recintos:true,turnos:true}}}}))));
empresas.post('/',asyncHandler(async(req,res)=>{const {admin:adminInput,...raw}=req.body;const data=schema.parse(raw);const adminData=z.object({full_name:z.string().min(2),email:z.string().email(),password:z.string().min(10)}).parse(adminInput);const result=await db.$transaction(async tx=>{const empresa=await tx.empresa.create({data});const user=await tx.user.create({data:{...adminData,password:await bcrypt.hash(adminData.password,12),role:'admin',empresa_id:empresa.id,email_verified:true,must_change_password:true,permisos:Object.fromEntries(modules.map(x=>[x,true]))}});return{empresa,admin:publicUser(user)}});await audit('crear_empresa',{userId:req.user!.id,entity:'empresa',entityId:result.empresa.id});res.status(201).json(result);}));
empresas.put('/:id',asyncHandler(async(req,res)=>{const data=schema.partial().parse(req.body);const empresa=await db.empresa.update({where:{id:req.params.id},data});if(empresa.estado!=='Activa')await db.session.updateMany({where:{user:{empresa_id:empresa.id},revoked_at:null},data:{revoked_at:new Date()}});await audit('editar_empresa',{userId:req.user!.id,entity:'empresa',entityId:empresa.id});res.json(empresa);}));
empresas.delete('/:id',asyncHandler(async(req,res)=>{await db.empresa.update({where:{id:req.params.id},data:{estado:'Eliminada'}});await db.user.updateMany({where:{empresa_id:req.params.id},data:{enabled:false}});await db.session.updateMany({where:{user:{empresa_id:req.params.id},revoked_at:null},data:{revoked_at:new Date()}});res.status(204).end();}));
empresas.put('/:id/admin-password',asyncHandler(async(req,res)=>{const {user_id,password}=z.object({user_id:z.string(),password:z.string().min(10)}).parse(req.body);const user=await db.user.findFirstOrThrow({where:{id:user_id,empresa_id:req.params.id,role:'admin'}});await db.user.update({where:{id:user.id},data:{password:await bcrypt.hash(password,12),must_change_password:true,enabled:true}});await db.session.updateMany({where:{user_id:user.id,revoked_at:null},data:{revoked_at:new Date()}});res.json({message:'Acceso administrativo restablecido'});}));
