import { Router } from 'express';
import { audit as persistAudit,db,sendEmail,sendTelegram } from './lib.js';
import { admin,asyncHandler,permit } from './middleware.js';
import { uploadNextcloud } from './nextcloud.js';

export const rrhh=Router();
rrhh.use(permit('rrhh'));
const dates=new Set(['fecha_nacimiento','fecha_ingreso','fecha_termino','fecha_inicio','fecha_fin','fecha_hecho','fecha_notificacion']);
const clean=(body:any,allowed:string[])=>Object.fromEntries(Object.entries(body).filter(([key])=>allowed.includes(key)).map(([key,value])=>[key,dates.has(key)&&value?new Date(String(value)):value===''?null:value]));
const workerFields=['nombre','documento','fecha_nacimiento','nacionalidad','direccion','comuna','telefono','email_personal','email_corporativo','contacto_emergencia_nombre','contacto_emergencia_parentesco','contacto_emergencia_telefono','cargo','area','supervisor','recinto','fecha_ingreso','tipo_contrato','jornada','estado','fecha_termino','motivo_termino','observaciones','foto_url','guardia_id','user_id'];
const eventFields=['tipo','titulo','fecha_inicio','fecha_fin','estado','dias','detalle','entidad','folio','archivo_url','archivo_cloud_path','confidencial','notificar_email','notificar_telegram'];
const warningFields=['fecha_hecho','lugar','tipo_incumplimiento','hechos','norma_relacionada','descargos','medida','responsable','testigos','fecha_notificacion','estado','constancia_recepcion'];
const audit=(req:any,accion:string,entidad:string,entidadId:string)=>persistAudit(`rrhh_${accion}`,{userId:req.user?.id,entity:entidad,entityId:entidadId,ip:req.ip,userAgent:req.get('user-agent')});

// Al entrar a RR. HH. incorpora los guardias y usuarios existentes. Solo se
// actualizan datos compartidos; el contenido propio del expediente se conserva.
async function performPeopleSync(){
  const [guardias,users]=await Promise.all([
    db.guardia.findMany(),
    db.user.findMany({where:{empresa_id:{not:null}},select:{id:true,empresa_id:true,guardia_id:true,full_name:true,email:true,telefono:true,cargo:true,rango:true,role:true,enabled:true,foto_url:true}})
  ]);
  const validGuardIds=guardias.map(guardia=>guardia.id);
  // Repara fichas cuyo guardia fue eliminado. El expediente laboral se
  // conserva, pero vuelve a quedar disponible para una futura reincorporación.
  await db.trabajador.updateMany({where:{guardia_id:{not:null},...(validGuardIds.length?{NOT:{guardia_id:{in:validGuardIds}}}:{})},data:{guardia_id:null}});
  const usersByGuardia=new Map<string,any>(users.filter(user=>user.guardia_id).map(user=>[user.guardia_id!,user]));
  for(const guardia of guardias){
    const linkedUser=usersByGuardia.get(guardia.id);
    const existing=await db.trabajador.findFirst({where:{OR:[{guardia_id:guardia.id},{documento:guardia.documento},...(linkedUser?[{user_id:linkedUser.id}]:[])]}});
    const shared={nombre:guardia.nombre,telefono:guardia.telefono,email_corporativo:linkedUser?.email||guardia.email,cargo:linkedUser?.cargo||String(guardia.rango).replaceAll('_',' '),recinto:guardia.recinto_nombre,estado:guardia.estado==='Activo'?'Activo':String(guardia.estado),foto_url:linkedUser?.foto_url||guardia.foto_url,guardia_id:guardia.id,...(linkedUser?{user_id:linkedUser.id}:{})};
    if(existing)await db.trabajador.update({where:{id:existing.id},data:existing.estado==='Archivado'?{...shared,estado:'Archivado'}:shared});
    else await db.trabajador.create({data:{...shared,empresa_id:guardia.empresa_id,documento:guardia.documento,fecha_ingreso:guardia.fecha_ingreso}});
  }
  for(const user of users){
    if(user.guardia_id)continue;
    const existing=await db.trabajador.findFirst({where:{OR:[{user_id:user.id},{email_corporativo:user.email},{email_personal:user.email}]}});
    const shared={nombre:user.full_name,telefono:user.telefono,email_corporativo:user.email,cargo:user.cargo||String(user.rango||user.role).replaceAll('_',' '),estado:user.enabled?'Activo':'Inactivo',foto_url:user.foto_url,user_id:user.id};
    if(existing)await db.trabajador.update({where:{id:existing.id},data:existing.estado==='Archivado'?{...shared,estado:'Archivado'}:shared});
    else await db.trabajador.create({data:{...shared,empresa_id:user.empresa_id!,documento:`USR-${user.id}`}});
  }
}
let syncInProgress:Promise<void>|null=null;
const syncRegisteredPeople=()=>{if(!syncInProgress)syncInProgress=performPeopleSync().finally(()=>{syncInProgress=null});return syncInProgress};

rrhh.get('/resumen',asyncHandler(async(_req,res)=>{await syncRegisteredPeople();const today=new Date();const month=new Date(today.getFullYear(),today.getMonth(),1);const [activos,inactivos,suspendidos,licencias,ausencias,amonestaciones,contratos,archivados]=await Promise.all([db.trabajador.count({where:{estado:'Activo'}}),db.trabajador.count({where:{estado:{in:['Inactivo','Desvinculado']}}}),db.trabajador.count({where:{estado:'Suspendido'}}),db.trabajador.count({where:{estado:'Licencia'}}),db.eventoRRHH.count({where:{tipo:'Inasistencia',fecha_inicio:{gte:month}}}),db.amonestacion.count({where:{fecha_hecho:{gte:month}}}),db.trabajador.count({where:{fecha_termino:{gte:today},estado:{not:'Archivado'}}}),db.trabajador.count({where:{estado:'Archivado'}})]);res.json({activos,inactivos,suspendidos,licencias,ausencias,amonestaciones,contratos,archivados});}));
rrhh.get('/alertas-vencimiento',asyncHandler(async(req,res)=>{const days=Math.min(365,Math.max(1,Number(req.query.dias||60))),today=new Date(),limit=new Date(today.getTime()+days*86400_000);const[contratos,credenciales]=await Promise.all([db.trabajador.findMany({where:{fecha_termino:{gte:today,lte:limit}},select:{id:true,nombre:true,fecha_termino:true,tipo_contrato:true},orderBy:{fecha_termino:'asc'}}),db.eventoRRHH.findMany({where:{tipo:{in:['Credencial','Curso','OS10','Certificación']},fecha_fin:{gte:today,lte:limit}},include:{trabajador:{select:{nombre:true}}},orderBy:{fecha_fin:'asc'}})]);res.json({dias:days,contratos,credenciales,total:contratos.length+credenciales.length});}));
rrhh.get('/trabajadores-exportar',asyncHandler(async(req,res)=>{const archived=req.query.archivados==='true',rows=await db.trabajador.findMany({where:{estado:archived?'Archivado':{not:'Archivado'}},include:{_count:{select:{eventos:true,amonestaciones:true}}},orderBy:{nombre:'asc'}}),headers=['Nombre','RUT / Documento','Cargo','Estado','Teléfono','Correo personal','Correo corporativo','Área','Supervisor','Recinto','Fecha de ingreso','Tipo de contrato','Jornada','Fecha de término','Registros','Amonestaciones'],values=rows.map(x=>[x.nombre,x.documento,x.cargo,x.estado,x.telefono,x.email_personal,x.email_corporativo,x.area,x.supervisor,x.recinto,x.fecha_ingreso?.toISOString().slice(0,10),x.tipo_contrato,x.jornada,x.fecha_termino?.toISOString().slice(0,10),x._count.eventos,x._count.amonestaciones]);res.setHeader('Content-Disposition',`attachment; filename="trabajadores-${new Date().toISOString().slice(0,10)}.csv"`);res.type('text/csv').send('\ufeff'+[headers,...values].map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(';')).join('\n'));}));
rrhh.get('/trabajadores',asyncHandler(async(req,res)=>{await syncRegisteredPeople();const q=String(req.query.q||''),archivados=req.query.archivados==='true';const data=await db.trabajador.findMany({where:{estado:archivados?'Archivado':{not:'Archivado'},...(q?{OR:[{nombre:{contains:q}},{documento:{contains:q}},{cargo:{contains:q}}]}:{})},include:{_count:{select:{eventos:true,amonestaciones:true}}},orderBy:{nombre:'asc'}});res.json(data);}));
rrhh.post('/trabajadores',admin,asyncHandler(async(req,res)=>{const data:any=clean(req.body,workerFields);if(!data.nombre||!data.documento||!data.cargo)return res.status(400).json({message:'Nombre, documento y cargo son obligatorios'});const item=await db.trabajador.create({data:{...data,empresa_id:req.user!.empresa_id!,created_by_id:req.user!.id}});audit(req,'crear','trabajador',item.id);res.status(201).json(item);}));
rrhh.get('/trabajadores/:id',asyncHandler(async(req,res)=>{const item=await db.trabajador.findUniqueOrThrow({where:{id:req.params.id},include:{eventos:{orderBy:{fecha_inicio:'desc'}},amonestaciones:{orderBy:{fecha_hecho:'desc'}}}});audit(req,'ver','trabajador',item.id);res.json(item);}));
rrhh.put('/trabajadores/:id',admin,asyncHandler(async(req,res)=>{const item=await db.trabajador.update({where:{id:req.params.id},data:clean(req.body,workerFields)});audit(req,'editar','trabajador',item.id);res.json(item);}));
rrhh.delete('/trabajadores/:id',admin,asyncHandler(async(req,res)=>{const item=await db.trabajador.findUniqueOrThrow({where:{id:req.params.id},include:{_count:{select:{eventos:true,amonestaciones:true}}}});if(item.guardia_id||item.user_id)return res.status(409).json({message:'Este trabajador está vinculado a un guardia o usuario. Desvincúlalo o desactiva su cuenta antes de eliminarlo'});await db.trabajador.delete({where:{id:item.id}});audit(req,'eliminar','trabajador',item.id);res.json({message:`Trabajador eliminado junto con ${item._count.eventos} registros y ${item._count.amonestaciones} amonestaciones`});}));
rrhh.post('/trabajadores/:id/archivar',admin,asyncHandler(async(req,res)=>{const worker=await db.trabajador.findUniqueOrThrow({where:{id:req.params.id}});await db.$transaction(async tx=>{await tx.trabajador.update({where:{id:worker.id},data:{estado:'Archivado'}});if(worker.guardia_id)await tx.guardia.updateMany({where:{id:worker.guardia_id},data:{estado:'Inactivo'}});if(worker.user_id)await tx.user.updateMany({where:{id:worker.user_id},data:{enabled:false}})});audit(req,'archivar','trabajador',worker.id);res.json({message:`${worker.nombre} fue archivado. Su expediente se conserva completo.`});}));
rrhh.post('/trabajadores/:id/restaurar',admin,asyncHandler(async(req,res)=>{const worker=await db.trabajador.update({where:{id:req.params.id},data:{estado:'Inactivo'}});audit(req,'restaurar','trabajador',worker.id);res.json({message:`${worker.nombre} fue restaurado como inactivo.`});}));
rrhh.post('/trabajadores/:id/convertir-guardia',admin,asyncHandler(async(req,res)=>{
  const empresaId=req.user!.empresa_id!;
  let worker=await db.trabajador.findFirst({where:{id:req.params.id,empresa_id:empresaId}});
  if(!worker)return res.status(404).json({message:'Trabajador no encontrado en esta empresa'});
  if(worker.guardia_id){const linked=await db.guardia.findFirst({where:{id:worker.guardia_id,empresa_id:empresaId}});if(linked)return res.status(409).json({message:'El trabajador ya está vinculado a un guardia'});worker=await db.trabajador.update({where:{id:worker.id},data:{guardia_id:null}})}
  const rango=String(req.body.rango||'guardia');
  if(!['supervisor','guardia_senior','guardia','cabo','conserje','nochero'].includes(rango))return res.status(400).json({message:'Rango de guardia inválido'});
  const company=await db.empresa.findUniqueOrThrow({where:{id:empresaId}});
  if(company.limite_guardias&&await db.guardia.count({where:{empresa_id:empresaId}})>=company.limite_guardias)return res.status(409).json({message:'La empresa alcanzó el límite de guardias contratado'});
  const duplicate=await db.guardia.findFirst({where:{documento:worker.documento}});
  if(duplicate)return res.status(409).json({message:duplicate.empresa_id===empresaId?'Ya existe un guardia con el documento de este trabajador':'El documento del trabajador ya está registrado como guardia en otra empresa'});
  const site=req.body.recinto_id?await db.recinto.findFirst({where:{id:String(req.body.recinto_id),empresa_id:empresaId}}):worker.recinto?await db.recinto.findFirst({where:{nombre:worker.recinto,empresa_id:empresaId}}):null;
  const guard=await db.$transaction(async tx=>{
    const created=await tx.guardia.create({data:{empresa_id:empresaId,nombre:worker.nombre,documento:worker.documento,telefono:worker.telefono,email:worker.email_corporativo||worker.email_personal,rango:rango as any,estado:worker.estado==='Activo'?'Activo':'Inactivo',fecha_ingreso:worker.fecha_ingreso,foto_url:worker.foto_url,recinto_id:site?.id,recinto_nombre:site?.nombre||worker.recinto,created_by_id:req.user!.id}});
    await tx.trabajador.update({where:{id:worker.id},data:{guardia_id:created.id,recinto:site?.nombre||worker.recinto,cargo:worker.cargo||'Guardia'}});
    if(worker.user_id){const linkedUser=await tx.user.updateMany({where:{id:worker.user_id,empresa_id:empresaId},data:{guardia_id:created.id,rango:rango as any,enabled:worker.estado==='Activo'}});if(!linkedUser.count)await tx.trabajador.update({where:{id:worker.id},data:{user_id:null}})}
    return created;
  });
  audit(req,'convertir_guardia','trabajador',worker.id);res.status(201).json({message:'Trabajador convertido en guardia sin duplicar su ficha',guardia:guard});
}));

rrhh.post('/trabajadores/:id/eventos',asyncHandler(async(req,res)=>{const worker=await db.trabajador.findFirstOrThrow({where:{id:req.params.id,empresa_id:req.user!.empresa_id!}}),data:any=clean(req.body,eventFields);if(!data.tipo||!data.titulo||!data.fecha_inicio)return res.status(400).json({message:'Tipo, título y fecha son obligatorios'});if(req.body.guardar_nextcloud&&data.archivo_url)data.archivo_cloud_path=await uploadNextcloud(worker,{dataUrl:data.archivo_url,name:String(req.body.archivo_nombre||`${data.tipo}.pdf`)});const item=await db.eventoRRHH.create({data:{...data,empresa_id:req.user!.empresa_id!,trabajador_id:req.params.id,created_by_id:req.user!.id}});audit(req,'crear',data.tipo,item.id);res.status(201).json(item);}));
rrhh.put('/eventos/:id',asyncHandler(async(req,res)=>{const item=await db.eventoRRHH.update({where:{id:req.params.id},data:clean(req.body,eventFields)});audit(req,'editar','evento',item.id);res.json(item);}));

let notificationRun:Promise<void>|null=null;
export function processRrhhNotifications(){
 if(notificationRun)return notificationRun;
 notificationRun=(async()=>{const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);
  const events=await db.eventoRRHH.findMany({where:{OR:[{fecha_inicio:{gte:start,lt:end},inicio_notificado_at:null},{fecha_fin:{gte:start,lt:end},termino_notificado_at:null}]},include:{trabajador:true}});
  const config=await db.configuracion.findUnique({where:{id:1}});
  for(const item of events){for(const phase of ['inicio','termino'] as const){const due=phase==='inicio'?item.fecha_inicio:item.fecha_fin,sent=phase==='inicio'?item.inicio_notificado_at:item.termino_notificado_at;if(!due||sent||due<start||due>=end)continue;
    const label=phase==='inicio'?'Inicio':'Término';const text=`${label} de registro RR. HH.\nTrabajador: ${item.trabajador.nombre}\nTipo: ${item.tipo}\nRegistro: ${item.titulo}\nFecha: ${due.toLocaleDateString('es-CL')}`;
    let delivered=false;if(item.notificar_email&&config?.notification_email){await sendEmail(config.notification_email,`${label}: ${item.tipo} — ${item.trabajador.nombre}`,text);delivered=true}if(item.notificar_telegram){await sendTelegram(text);delivered=true}if(delivered)await db.eventoRRHH.update({where:{id:item.id},data:phase==='inicio'?{inicio_notificado_at:new Date()}:{termino_notificado_at:new Date()}});
  }}
 })().catch(error=>console.error('Error en avisos de RR. HH.',error)).finally(()=>{notificationRun=null});return notificationRun;
}

rrhh.post('/trabajadores/:id/amonestaciones',admin,asyncHandler(async(req,res)=>{const data:any=clean(req.body,warningFields);if(!data.fecha_hecho||!data.tipo_incumplimiento||!data.hechos||!data.responsable)return res.status(400).json({message:'Fecha, incumplimiento, hechos y responsable son obligatorios'});const folio=`AM-${new Date().getFullYear()}-${String((await db.amonestacion.count({where:{empresa_id:req.user!.empresa_id!}}))+1).padStart(5,'0')}`;const item=await db.amonestacion.create({data:{...data,empresa_id:req.user!.empresa_id!,folio,trabajador_id:req.params.id,created_by_id:req.user!.id}});audit(req,'emitir','amonestacion',item.id);res.status(201).json(item);}));
rrhh.put('/amonestaciones/:id',admin,asyncHandler(async(req,res)=>{const existing=await db.amonestacion.findUniqueOrThrow({where:{id:req.params.id}});if(existing.estado!=='Borrador'&&req.body.estado!=='Anulada')return res.status(409).json({message:'Una amonestación emitida no puede modificarse; anúlala y crea una nueva versión'});const item=await db.amonestacion.update({where:{id:req.params.id},data:clean(req.body,warningFields)});audit(req,'editar','amonestacion',item.id);res.json(item);}));

async function warningHtml(id:string){const [item,config]=await Promise.all([db.amonestacion.findUniqueOrThrow({where:{id},include:{trabajador:true}}),db.configuracion.findUnique({where:{id:1}})]);const esc=(value:any)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(item.folio)}</title><style>@page{size:A4;margin:22mm}body{font:14px Arial;color:#172033;line-height:1.5}.head{display:flex;align-items:center;border-bottom:3px solid #0d9488;padding-bottom:16px;margin-bottom:25px}.logo{max-height:65px;max-width:180px}.brand{margin-left:18px}h1{font-size:21px;margin:0}.folio{margin-left:auto;text-align:right}.box{border:1px solid #cbd5e1;border-radius:8px;padding:14px;margin:14px 0}h2{font-size:14px;color:#0f766e;text-transform:uppercase}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:80px}.signature{border-top:1px solid #334155;text-align:center;padding-top:8px}.footer{margin-top:50px;font-size:11px;color:#64748b;text-align:center}@media print{button{display:none}}</style></head><body><button onclick="print()">Imprimir / Guardar PDF</button><div class="head">${config?.logo_url?`<img class="logo" src="${config.logo_url}">`:''}<div class="brand"><h1>${esc(config?.brand_name||'Seguridad')}</h1><div>${esc(config?.brand_subtitle||'Recursos Humanos')}</div></div><div class="folio"><b>${esc(item.folio)}</b><br>${new Date(item.fecha_hecho).toLocaleDateString('es-CL')}</div></div><h1>Carta de amonestación</h1><div class="box"><b>Trabajador:</b> ${esc(item.trabajador.nombre)}<br><b>Documento:</b> ${esc(item.trabajador.documento)}<br><b>Cargo:</b> ${esc(item.trabajador.cargo)}<br><b>Lugar:</b> ${esc(item.lugar||item.trabajador.recinto)}</div><h2>Incumplimiento</h2><p><b>${esc(item.tipo_incumplimiento)}</b></p><h2>Descripción objetiva de los hechos</h2><p>${esc(item.hechos)}</p>${item.norma_relacionada?`<h2>Norma relacionada</h2><p>${esc(item.norma_relacionada)}</p>`:''}${item.descargos?`<h2>Descargos del trabajador</h2><p>${esc(item.descargos)}</p>`:''}${item.medida?`<h2>Medida adoptada</h2><p>${esc(item.medida)}</p>`:''}<div class="signatures"><div class="signature">${esc(item.responsable)}<br>Representante del empleador</div><div class="signature">${esc(item.trabajador.nombre)}<br>Trabajador/a</div></div><div class="footer">Documento ${esc(item.folio)} · Generado por Seguridad RRHH · Conserve una copia en el expediente laboral.</div></body></html>`}
rrhh.get('/amonestaciones/:id/documento',asyncHandler(async(req,res)=>{audit(req,'imprimir','amonestacion',req.params.id);res.json({html:await warningHtml(req.params.id)})}));
rrhh.post('/amonestaciones/:id/enviar',admin,asyncHandler(async(req,res)=>{const item=await db.amonestacion.findUniqueOrThrow({where:{id:req.params.id},include:{trabajador:true}});const email=item.trabajador.email_corporativo||item.trabajador.email_personal;if(!email)return res.status(400).json({message:'El trabajador no tiene correo registrado'});await sendEmail(email,`Carta de amonestación ${item.folio}`,`Se adjunta para notificación el documento ${item.folio}.\n\nIncumplimiento: ${item.tipo_incumplimiento}\nFecha del hecho: ${item.fecha_hecho.toLocaleDateString('es-CL')}\n\nIngresa a la plataforma o solicita una copia impresa a Recursos Humanos.`);await db.amonestacion.update({where:{id:item.id},data:{enviada_email_at:new Date(),estado:item.estado==='Borrador'?'Notificada':item.estado}});audit(req,'enviar_correo','amonestacion',item.id);res.json({message:`Amonestación enviada a ${email}`});}));
